### ISSUE TITLE
Apple M1 [FATAL] Error while cataloging RMAN Backups

### ISSUE THREAD

**Issue by fahrican** [gvenzl/oci-oracle-xe#101]
Because of my Apple M1 chip I cloned the repository and tried to build the image locally.

After I was running the commands:

`docker run -it gvenzl/oracle-xe:18.4.0-slim`

and

`/install/install.1840.sh "${BUILD_MODE}"`

I received following message:

```
Prepare for db operation
7% complete
Copying database files
8% complete
[WARNING] ORA-12547: TNS:lost contact

29% complete
100% complete
[FATAL] Error while cataloging RMAN Backups
7% complete
0% complete
Look at the log file "/opt/oracle/cfgtoollogs/dbca/XE/XE.log" for further details.

Database configuration failed. Check logs under '/opt/oracle/cfgtoollogs/dbca'.
```

Then I took a look into the **XE.log** file

I received this:

```
[ 2022-04-05 12:11:46.298 UTC ] [WARNING] [DBT-09251] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
[ 2022-04-05 12:11:49.239 UTC ] Prepare for db operation
DBCA_PROGRESS : 7%
[ 2022-04-05 12:11:50.225 UTC ] Copying database files
DBCA_PROGRESS : 8%
[ 2022-04-05 12:11:51.574 UTC ] [WARNING] ORA-12547: TNS:lost contact

DBCA_PROGRESS : 29%
DBCA_PROGRESS : 100%
[ 2022-04-05 12:11:52.716 UTC ] [FATAL] Error while cataloging RMAN Backups
DBCA_PROGRESS : 7%
DBCA_PROGRESS : 0%
bash-4.4#
```

**Comment by gvenzl** [comment]
Hi @fahrican,

Unfortunately, Oracle Database is not supported on Apple M1 as of right now. See [this discussion over at github.com/oracle/docker-images](https://github.com/oracle/docker-images/discussions/1951) for more information.

People seem to have found a workaround via `colima` but I cannot verify nor guarantee that.
