### ISSUE TITLE
expose create_app_user as a callable script

### ISSUE THREAD

**Issue by crowne** [gvenzl/oci-oracle-xe#102]
I have initialization scripts where I would like to create additional app users.
I'd like to be able to call the existing function create_app_user in container-entrypoint.sh
Could this be exposed as a standalone callable script like /opt/oracle/resetPassword

**Comment by gvenzl** [comment]
Hey @crowne, 

What's wrong with running the initialization scripts through the [initialization scripts mechanism](https://github.com/gvenzl/oci-oracle-xe#initialization-scripts)?

**Comment by crowne** [comment]
Hi Gerald,

There's nothing wrong with the existing initialization script mechanism I am using this mechanism,  
however as part of my initialization I need to create additional app users.  

In doing so, I wanted to avoid writing multiple create user scripts and rather call a single script multiple times passing the username and password as parameters.  

This is already done in the existing function `create_app_user` in `container-entrypoint.sh`
However I can't call that existing function from my initialization scripts,  
so my suggestion is to extract it out of `container-entrypoint.sh` making it into a standalone callable script  
which can be called by `container-entrypoint.sh` as well as by additional initialization scripts if necessary.

**Comment by gvenzl** [comment]
Hey @crowne,

Ah I see, that does make sense and I can see how that functionality can come in handy for other situations as well.
I saw your PR, thanks a lot for that.
I would like to modularize it a bit further, i.e. not having the same logic twice, but I'm happy to do that change myself once we merge it.
Could I just please ask you to file the PR against the `development` branch and not `main`?

**Comment by gvenzl** [comment]
Actually, strike the last part, I was able to change the target branch myself.
Thanks a lot, @crowne, will now work on the modularization part.

**Comment by gvenzl** [comment]
This is now available in all images.
