### ISSUE TITLE
`container-entrypoint.sh` fails on systems with 32 logical cpus

### ISSUE THREAD

**Issue by GertBurger** [gvenzl/oci-oracle-xe#104]
Tested on 18.4.0-slim

```
/opt/oracle/container-entrypoint.sh: line 156: ((: 32 = 32 : attempted assignment to non-variable (error token is "= 32 ")
```

If I have to guess I would say that the `=` should be `==`

**Comment by gvenzl** [comment]
Hi @GertBurger,

You are correct, should have been `==`, will fix it ASAP!
Thanks for spotting and reporting it!

**Comment by gvenzl** [comment]
New images with this fix are now live.

**Comment by GertBurger** [comment]
Thanks! It's working great now :+1:
