### ISSUE TITLE
Max String Size Extended / Reusing Existing Tablespaces with data

### ISSUE THREAD

**Issue by dolphin54** [gvenzl/oci-oracle-xe#106]
Hi, 
Nice work on the docker image thanks.

Would be good if you can manage to have the image already with 'max string size' in extended mode instead of 'standard' (or an easy way to do it.
At the moment I have it on a startup script and always needs couple of shutdowns and startups with and without upgrade option. Which does take a while to do. Then I will try attaching exiting volumes (tablespaces). Ideally be in a position where I left off last time I used it.
In essence, what everyone wants from all this.  But trying to do all this, is very hard. (btw i am running docker on windows).

So ideally, first setup a DB with extended max string size and tablespaces:
-> with windows mapping directories for the dbs path, startup script.
o set max string size extended 
https://smarttechways.com/2022/02/11/ora-43929-collation-cannot-be-specified-if-parameter-max_string_sizestandard/
o create tablespaces
o create users
o create tables etc...
o populate the tables
o export the tablespaces (as I guess this is the only way to use again)
o bash logon to export the associate dump file

Then further restarts can be:
-> with windows mapping directories for the dbs path, startup script.
o set max string size extended 
o load tablespaces
o create users

For me, having as much of this as part of the image or easily to do it would make the image useful. Trying to load up a chunks of data every time just takes to long to make it useful.
I hope I am doing it all the right way.
Please let me know.
Thanks in advance,
Den

**Comment by gvenzl** [comment]
Hi @dolphin54,

Thanks a lot for using these images!

I am hesitant to deviate too much from the standard Oracle XE setup as I want to ensure that people get the same "look and feel" that they would get from any other Oracle XE installation.
Deviating from it may make people and their software rely on certain functionality that they then will not have somewhere else, causing more pain further down the road.

When you attach an existing volume with tablespaces, could you not just attach a database with max_string_size already configured altogether?
The image is smart enough to detect an already existing database and will just start it up.
So as long as you save the entire `oradata` folder which includes the database and config files, you should just get back to where you left off right there.

An alternative approach could be to extend the image, where the max_string_size configuration is performed once and a new image then generated.

**Comment by mrmanc** [comment]
We ran into the same thing today, and went about extending the image using the approach described in #187. It takes a few minutes to build the extra layer, but the below Dockerfile (and sql script) mostly authored by Claude should work for you.

## Dockerfile
```
# syntax=docker/dockerfile:1

FROM gvenzl/oracle-xe:21-slim-faststart

# This becomes the PERMANENT SYS/SYSTEM password baked into this image.
# Any ORACLE_PASSWORD you pass to `docker run` later will be silently
# IGNORED, because the entrypoint will see the database is already
# initialized and skip password setup entirely. Override this at build
# time with --build-arg ORACLE_PASSWORD=... and record what you used.
ARG ORACLE_PASSWORD=ChangeMe_BuildPwd1

COPY --chown=oracle:oracle max_string_size.sql /tmp/max_string_size.sql

RUN container-entrypoint.sh --nowait && \
    echo "CONTAINER: applying MAX_STRING_SIZE=EXTENDED..." && \
    sqlplus -s / as sysdba @/tmp/max_string_size.sql && \
    echo "CONTAINER: upgrade complete, shutting down for image commit..." && \
    echo "shutdown immediate;" | sqlplus -s / as sysdba && \
    lsnrctl stop && \
    rm -f /tmp/max_string_size.sql

# At runtime, the entrypoint will detect the database is already
# initialized and just start it + the listener - no password vars needed,
# no first-time setup, no upgrade steps re-run.
```

## max_string_size.sql
```
-- max_string_size.sql
-- Enables MAX_STRING_SIZE=EXTENDED for both the CDB root and the XEPDB1
-- application PDB. Run as SYS (OS/bequeath auth, e.g. "sqlplus / as sysdba")
-- while the instance was started with container-entrypoint.sh --nowait.
--
-- Fail the whole script (and therefore the Docker build) loudly on any error,
-- rather than silently committing a half-upgraded image.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO ON
SET FEEDBACK ON

-- 1) Bounce into UPGRADE mode and set the parameter in the SPFILE
SHUTDOWN IMMEDIATE;
STARTUP UPGRADE;
ALTER SYSTEM SET MAX_STRING_SIZE=EXTENDED SCOPE=SPFILE;

-- 2) Bounce again so the instance actually picks up the new SPFILE value
--    (MAX_STRING_SIZE requires a restart to take effect, even in UPGRADE mode)
SHUTDOWN IMMEDIATE;
STARTUP UPGRADE;

-- 3) Recompile dependent views/objects in the CDB root
@?/rdbms/admin/utl32k.sql

-- 4) Do the same inside the XEPDB1 application PDB - MAX_STRING_SIZE views
--    need to be recompiled per-container, not just in the root
ALTER PLUGGABLE DATABASE XEPDB1 OPEN UPGRADE;
ALTER SESSION SET CONTAINER=XEPDB1;
@?/rdbms/admin/utl32k.sql
ALTER SESSION SET CONTAINER=CDB$ROOT;

-- 5) Return to normal operation
SHUTDOWN IMMEDIATE;
STARTUP;
ALTER PLUGGABLE DATABASE XEPDB1 OPEN;
ALTER PLUGGABLE DATABASE XEPDB1 SAVE STATE;

-- 6) Sanity check - these are what you should see in the build log
SHOW PARAMETER MAX_STRING_SIZE;
SELECT NAME, OPEN_MODE, RESTRICTED FROM V$PDBS;

EXIT
