### ISSUE TITLE
Create init script directories by default.

### ISSUE THREAD

**Issue by TonyNoble** [gvenzl/oci-oracle-xe#108]
The /container-entrypoint-initdb.d and /container-entrypoint-startdb.d directories can be used for custom init/startup scripts, but they do not exist by default.  Additionally, because the container runs as the 'oracle' user, it is not possible to override the entrypoint to create and populate them.

Please could you consider creating these two directories as part of the image build and 'chown'ing them to the oracle user?

In particular, this would be particularly useful when using the container as a service for gitlab-ci without having to customise and keep a locally stored image.

**Comment by gvenzl** [comment]
Hi @TonyNoble,

First of all, thanks for using these images!

Podman / Docker automatically creates the directory when using volumes:

```bash
[gvenzl@localhost ~]$ podman run --entrypoint=bash --name test -ti -v ./test:/container-entrypoint-initdb.d gvenzl/oracle-xe:21-slim
bash-4.4$ ls -al /container-entrypoint-initdb.d/
total 0
drwxrwxr-x  4 root root 30 Apr 20 03:33 .
dr-xr-xr-x 18 root root 43 May 21 18:38 ..
drwxrwxr-x  2 root root 24 Mar 20 17:39 job
drwxrwxr-x  2 root root 60 Mar 20 17:36 netca
bash-4.4$ ls -al /
total 0
dr-xr-xr-x  18 root   root    54 May 21 18:38 .
lrwxrwxrwx   1 root   root     7 Oct  9  2021 bin -> usr/bin
dr-xr-xr-x   2 root   root     6 Oct  9  2021 boot
drwxrwxr-x   4 root   root    30 Apr 20 03:33 container-entrypoint-initdb.d
drwxr-xr-x   5 root   root   360 May 21 18:38 dev
drwxr-xr-x  36 root   root    22 May 21 18:38 etc
drwxr-xr-x   2 root   root     6 Oct  9  2021 home
lrwxrwxrwx   1 root   root     7 Oct  9  2021 lib -> usr/lib
lrwxrwxrwx   1 root   root     9 Oct  9  2021 lib64 -> usr/lib64
drwxr-xr-x   2 root   root     6 Oct  9  2021 media
drwxr-xr-x   2 root   root     6 Oct  9  2021 mnt
drwxr-xr-x   4 root   root    36 Apr 23 06:56 opt
dr-xr-xr-x 189 nobody nobody   0 May 21 18:38 proc
dr-xr-x---   2 root   root     6 Oct  9  2021 root
drwxr-xr-x  11 root   root   124 Apr 23 07:21 run
lrwxrwxrwx   1 root   root     8 Oct  9  2021 sbin -> usr/sbin
drwxr-xr-x   2 root   root     6 Oct  9  2021 srv
dr-xr-xr-x  13 nobody nobody   0 May 21 18:38 sys
drwxrwxrwt   3 root   root    21 Apr 23 07:21 tmp
drwxr-xr-x  12 root   root    94 Apr 23 06:56 usr
drwxr-xr-x  19 root   root    65 Apr 23 06:52 var
```

Is that mechanism not working for gitlab-ci?
How do you spin the containers up in your environment?

**Comment by TonyNoble** [comment]
Hi @gvenzl 

Thanks for the response and thanks for providing these images.  With GitLab-CI, the startup and teardown of the build containers is automated and based on a declarative job configuration file - we do not have the ability to specify volume mounts in the job configuration - all we are guaranteed is that the applicable repository is mounted under a known location (/builds/...)

What we do have, is the ability to override the entrypoint for the container.  This means we can copy files between locations before triggering the original entrypoint script, but in this case, /container-entrypoint-initdb.d doesn't exist and the container runs as 'oracle' user, meaning it doesn't have permission to create the directory in order to subsequently copy the startup files there.

If the startup script directories were created as part of the image build and left empty, I believe the docker / Kubernetes volume mounts should still work as intended?

For reference, I've included the applicable fragment of one of our job (.gitlab-ci.yml) files below.  When running in a Kubernetes cluster, the 'service' containers are started in the same pod as the main CI runner container and can then be accessed by the build process.  When running under a dockerised build, they're started in the same docker network.
<pre>
Verify:
  stage: build
  
  image: maven:3-openjdk-17

  services:
    - name: our.container.registry.com/oracle-xe:latest
      alias: oracle
      variables:
        ORACLE_PASSWORD: password
      entrypoint:
        - '/bin/bash'
        - '-c'
        - |
          # Wait for clone to complete and then copy init files
          echo "Waiting for mounted repo to become availble"
          until [ -f "${CI_PROJECT_DIR}/.git/index" ]; do sleep 1; done;
          while [ -f "${CI_PROJECT_DIR}/.git/index.lock" ]; do sleep 1; done;
          echo "Copying init scripts"
          cp "${CI_PROJECT_DIR}/src/test/resources/oracle/*.sql" /container-entrypoint-initdb.d/.
          echo "Starting Database"
          exec /opt/oracle/container-entrypoint.sh "$@"
          
  script:
    - mvn clean verify -P integrationTests
</pre>

**Comment by gvenzl** [comment]
Hi @TonyNoble,

Thanks a lot for that background, I was not aware that some CI solutions do not allow to map volumes or anything else sophisticated to make files available to the container. Adding the empty folders will have no downsides, I was just curious to understand why they are needed, makes perfect sense. I will add the creation of these to the build process so that they are available in the images.

**Comment by gvenzl** [comment]
Hey @TonyNoble,

`/container-entrypoint-initdb.d` and `/container-entrypoint-startdb.d` are now present inside all images.
Could you try again and see whether that works as expected and please report back here?

**Comment by TonyNoble** [comment]
Hi @gvenzl, that looks to solve our problem - thanks very much for your assistance.

**Comment by gvenzl** [comment]
Great, thanks for confirming!
