### ISSUE TITLE
Run container and entrypoint scripts in UTF-8 by default

### ISSUE THREAD

**Issue by mdahm** [gvenzl/oci-oracle-xe#109]
We have added scripts to import data at startup containing umlauts and other special characters.
However, this cause corrupt data in the tables. The reason is that that the NLS settings in the Oracle server do not
correspond with the ones of the (Linux container) client.

We were able to fix that with a Dockerfile like this:

```
FROM gvenzl/oracle-xe:21-slim

# Fix encoding issue on import
ENV LANG        "de_DE.UTF-8"
ENV NLS_LANG    "german_germany.utf8"
```

You should consider to merge this fix into the default settings...

See https://stackoverflow.com/questions/58394515/how-to-handle-umlaute-like-%C3%84-%C3%96-%C3%9C-in-coldfusion-sql-query-to-insert-into-database

**Comment by gvenzl** [comment]
Hi @mdahm,

Thanks a lot, I will get the `UTF-8` as default in the container and for the database instance but I'm afraid the `GERMAN_GERMANY` part is not really a fix that would work for everybody as anybody who doesn't want to have Germany as their territory would now have issues.

The good news is that these environment variables can be set dynamically, so everybody can opt to override them without having to build a new image. Even you can do so now, just pass the two environment variables on with, for example, the `-e` flag:

```
docker run --name test -e ORACLE_PASSWORD=LetsTest1 -e LANG=de_DE.UTF-8 -e NLS_LANG=german_germany.utf8 gvenzl/oracle-xe:21-slim
```

```
docker exec -ti test bash

bash-4.4$ set | grep -i lang
LANG=de_DE.UTF-8
NLS_LANG=german_germany.utf8

bash-4.4$ sqlplus / as sysdba

SQL*Plus: Release 21.0.0.0.0 - Production on Mo Jun 13 00:26:21 2022
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle.  All rights reserved.


Verbunden mit:
Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0

SQL> show parameter nls

NAME				     TYPE			       VALUE
------------------------------------ --------------------------------- ------------------------------
nls_calendar			     string			       GREGORIAN
nls_comp			     string			       BINARY
nls_currency                         string                            €
nls_date_format 		     string			       DD.MM.RR
nls_date_language		     string			       GERMAN
nls_dual_currency                    string                            €
nls_iso_currency		     string			       GERMANY
nls_language			     string			       GERMAN
nls_length_semantics		     string			       BYTE
nls_nchar_conv_excp		     string			       FALSE
nls_numeric_characters		     string			       ,.
nls_sort			     string			       GERMAN
nls_territory			     string			       GERMANY
nls_time_format 		     string			       HH24:MI:SSXFF
nls_timestamp_format		     string			       DD.MM.RR HH24:MI:SSXFF
nls_timestamp_tz_format 	     string			       DD.MM.RR HH24:MI:SSXFF TZR
nls_time_tz_format		     string			       HH24:MI:SSXFF TZR
```

Note how both the Linux OS and the database have received these parameters.

**Comment by gvenzl** [comment]
Fixed
