### ISSUE TITLE
21c image have many of the dashboard of EM Express empty, for example Performance Hub

### ISSUE THREAD

**Issue by marcelo-ochoa** [gvenzl/oci-oracle-xe#112]
21.30 image (full) have many of the EM Express dashboard empty.
This is caused by an empty v$active_session_history system view, to fix this issue is necessary to enable Diagnostic Pack by [default](https://community.oracle.com/tech/developers/discussion/4312940/ash-report-always-displays-no-data-exists-for-this-section-of-the-report-in-all-its-sections):
```sql
alter system set control_management_pack_access='DIAGNOSTIC+TUNING' scope=spfile;
shutdown immediate
startup
```
This can be done for example after the line [206](https://github.com/gvenzl/oci-oracle-xe/blob/main/install.2130.sh#L206) on install.2130 file.
Best regards, Marcelo.

**Comment by gvenzl** [comment]
Implemented

**Comment by marcelo-ochoa** [comment]
Thanks!!.

**Comment by marcelo-ochoa** [comment]
Gerald:
   When the updated image will be ready at Docker Host??
   Thanks a lot, Marcelo.
