### ISSUE TITLE
Unable to connect when running in Azure Container Instances

### ISSUE THREAD

**Issue by danielmarbach** [gvenzl/oci-oracle-xe#113]
When doing

```
az container create --image gvenzl/oracle-xe:21 --name foobar1 --dns-name-label foobar1 --cpu 4 --memory 8 --ports 1521 5500 --ip-address public --environment-variables ORACLE_PASSWORD=...
```

the images spins up and reports

```
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=SandboxHost-6378...)(PORT=5500))(Security=(my_wallet_directory=/opt/oracle/admin/XE/xdb_wallet))(Presentation=HTTP)(Session=RAW))
```

but then when I try to connect either over the public IP address of the container or the dns name and the port 1521 I cannot establish the connection.

```
jdbc:oracle:thin:@foobar1.REGION.azurecontainer.io:1521:XE
```

**Comment by gvenzl** [comment]
He @danielmarbach,

Thanks a lot for using these images!

Could you please also post the error that you are getting when connecting to the database?

First and foremost, you shouldn't use `:` between `1521` and `XE` but a `/` instead, i.e:

`jdbc:oracle:thin:@foobar1.REGION.azurecontainer.io:1521:XE` --> `jdbc:oracle:thin:@foobar1.REGION.azurecontainer.io:1521/XE`

A small but very important difference, however, has nothing to do with you not being able to connect to the database.
(you can get a [detailed explanation on this over here](https://github.com/gvenzl/oci-oracle-xe/issues/90#issuecomment-1059824208) if you are interested).

My gut feeling is that `foobar1.REGION.azurecontainer.io` probably doesn't map to the port forwarded or is being blocked.
I have seen in the past (with GitHub Actions) that the container port forwarding worked fine when using `localhost` that translated, obviously, back to 127.0.0.1 but not on the public IP that gets resolved with the hostname.
However, I have no experience at all with Azure Containers so this could be a complete red herring.
The error you are getting should tell us more on that though, so please provide that.

On another side note, the word `REGION` in `jdbc:oracle:thin:@foobar1.REGION.azurecontainer.io:1521:XE` sticks out to me, can it be that `REGION` should be the actual region that the container instance is in? I assume that `foobar1.REGION.azurecontainer.io` is pingable and resolved to an actual IP address, correct?

**Comment by danielmarbach** [comment]
Thanks for coming back on this issue!

Got it working. Honestly though I'm still a bit puzzled why. It seems the DNS propagation just took long. Extending the waiting time during the script helped. 

Thanks for clarifying the connection string too! Will look into this

Daniel

**Comment by gvenzl** [comment]
Sure thing, @danielmarbach!

Happy to hear that you got it working!
I will close this issue, feel free to reopen it or open a new one if you need anything else!

Thanks,

**Comment by gvenzl** [comment]
Great, thank you for the additional information, @danielmarbach!
I'm sure this will come in handy for other users!

**Comment by danielmarbach** [comment]
Thanks for coming back on this issue!Got it working. Honestly though I'm still a bit puzzled why. It seems the DNS propagation just took long. Extending the waiting time during the script helped. Thanks for clarifying the connection string too! Will look into thisDaniel

**Comment by amergey** [comment]
@danielmarbach  I have same issue, how did you extend the waiting time during the script ? in your github it seems you explain how to pass init script, but I do not see how you manager to have the ACI container started, thanks.

**Comment by danielmarbach** [comment]
@amergey Here is the code that does that

https://github.com/Particular/setup-oracle-action/blob/master/setup.ps1#L82-L91

You are welcome to steal whatever you need to make your scenario successful ;)
