### ISSUE TITLE
Oracle DB 21C Enterprise Edition Customization

### ISSUE THREAD

**Issue by karan-winfo** [gvenzl/oci-oracle-xe#114]
Hi There,

Right now I'm working on one project where I require to have few customization on the Oracle Database 21c XE installation in Oracle Linux 7.7. Please see the required things need to be change as given below. 
1) Database user should not be Oracle
2) Need to use different DB binary file location instead of /opt/oracle/...
3) CDB name should not be as XE.

I found that we can modify the configuration file is this "/etc/sysconfig/oracle-xe-21c.conf". But I am not sure how can I procced for these many changes in configuration file. 

Could you please help me on this?

**Comment by gvenzl** [comment]
Hi @karan-winfo,

I don't think that this question has anything to do with the images that I am providing here. Certainly, for Docker images, a user should not care about any details happening inside the Docker container.

Regardless of that, an XE installation cannot be changed to an EE installation.
The database user and path are both set up by the XE RPM installation itself and cannot be changed after the fact.
The `ORACLE_SID` and CDB for an Express Edition are always hard-coded to `XE`.

If you would like to have control over these settings, you will have to install either an SE2 or EE edition of Oracle Database.
