### ISSUE TITLE
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor.

### ISSUE THREAD

**Issue by bauerjan93** [gvenzl/oci-oracle-xe#126]
When i deploy the image to a service like AWS ECS or Kubernetes the database is setup correctly but while connecting from a client the connection is rejected with `ORA-12514, TNS:listener does not currently know of service requested in connect descriptor. ` When i run the image locally or on an separate instance the connection issue doesnt exist. What might cause this issue? I added in a second message the logs from the container, it seems the listener is not starting properly. 

Used jdbc string for connecting: `jdbc:oracle:thin:@<ip-address>:1521/XE`
I am using the default `gvenzl/oracle-xe` image.

**Comment by bauerjan93** [comment]
Issue still exists, so far i think this issue comes from different network modes available. When using a host with a network mode `bridge` the database listener works as expected. For network mode `awsvpc` and `host` the listener does not work correct. 

Different Network modes for AWS ECS (see:https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking.html):
`awsvpc`:The task is allocated its own elastic network interface (ENI) and a primary private IPv4 address. This gives the task the same networking properties as Amazon EC2 instances.
`bridge`: The task uses Docker's built-in virtual network, which runs inside each Amazon EC2 instance that hosts the task.
`host`: The task bypasses Docker's built-in virtual network and maps container ports directly to the ENI of the Amazon EC2 instance that hosts the task. As a result, you can't run multiple instantiations of the same task on a single Amazon EC2 instance when port mappings are used.

Does the database image need a specific network mode?

**Comment by bauerjan93** [comment]
Resolved by making changes to the VPC. Set enable_dns_hostnames = true.

**Comment by gvenzl** [comment]
Hi @bauerjan93,

Glad to see that your issue was resolved and thanks a lot for the detailed information. This will help other users running into the same issue!

Last but not least, thanks for using these images!
