### ISSUE TITLE
[QUESTION] Any way to not include the initial database?

### ISSUE THREAD

**Issue by aleybovich** [gvenzl/oci-oracle-xe#130]
I just ran the latest slim version and looking at the database I see a large number of empty tables (e.g. LOGMNR_*, MVIEW$_*) and schemas - what is the purpose of those? Is there an easy way to run the image with a blank db?

**Comment by gvenzl** [comment]
Hi @aleybovich,

These are all part of the Oracle Database data dictionary.
The first is for a feature called [LogMiner](https://docs.oracle.com/en/database/oracle/oracle-database/21/sutil/oracle-logminer-utility.html#GUID-3417B738-374C-4EE3-B15C-3A66E01AE2B5), the second is the dictionary table containing information about materialized views.

Likewise, the schemas are for various different features or administrative purposes, see, for example, [here](https://docs.oracle.com/en/database/oracle/oracle-database/21/admin/getting-started-with-database-administration.html#GUID-79AB6187-1522-4EB7-8FAD-E4322262AC65).

In essence, a DB with all these schemas and tables is a blank DB. If you were to delete some of those, some functionality will ultimately not work anymore.

Hope this helps!
