### ISSUE TITLE
Container Failed to Start

### ISSUE THREAD

**Issue by BagasNS** [gvenzl/oci-oracle-xe#134]
i run container by this command
```
docker run -d -p 1521:1521 -e ORACLE_PASSWORD=root -v [MY_ACTUAL_PATH]:/u01/app/oracle/oradata gvenzl/oracle-xe:11
```

i got error on log like this

![image](https://user-images.githubusercontent.com/36254694/187325219-ad9c91ac-29ec-40df-9217-9934c8519797.png)

when i start container without linking volume it running well, im using zorin os 16 with SELinux disabled

**Comment by gvenzl** [comment]
Hi @BagasNS,

The `oracle` user inside the container needs to have write permissions on the external volume directory. Please verify the permissions of the directory under [MY_ACTUAL_PATH].
