### ISSUE TITLE
third party software installation (e.g. java)

### ISSUE THREAD

**Issue by segaura** [gvenzl/oci-oracle-xe#136]
Hello.
In my current use case I have the need to install a third party software, specifically java.
In my understanding no package manager is available by default.
If it is feasible, which is the preferred way to go to achieve my goal?
(I am currently targeting 21-slim-faststart version)

EDIT: better looking at install.sh files I understand that `rpm` is available, maybe this is the solution

**Comment by gvenzl** [comment]
Hi @segaura,

Thank you for using these images!

`microdnf` is available inside the image.
For example, to install Java 17 OpenJDK, you can run the following:

```
FROM gvenzl/oracle-xe:21-slim-faststart
USER root
RUN microdnf install java-17-openjdk
```
