### ISSUE TITLE
Run Oracle as arbitrary user in Openshift

### ISSUE THREAD

**Issue by teceP** [gvenzl/oci-oracle-xe#145]
Is it possible to run gvenzl/oracle-xe:18-slim as an arbitrary user in OpenShift/Kubernetes?

If I try to run it, with modified Image with:

`RUN chgrp -R 0 $ORACLE_BASE && 
          chmod -R g+rwX $ORACLE_BASE`

which is mentioned in OpenShift documentary: https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidelines

Iam getting following failing startup process:

#############
#Log Start#####
#############
CONTAINER: starting up...
CONTAINER: database already initialized.
CONTAINER: starting up Oracle Database...

LSNRCTL for Linux: Version 18.0.0.0.0 - Production on 07-OCT-2022 17:05:34

Copyright (c) 1991, 2018, Oracle.  All rights reserved.

Starting /opt/oracle/product/18c/dbhomeXE/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 18.0.0.0.0 - Production
System parameter file is /opt/oracle/product/18c/dbhomeXE/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/oracle-keycloak-int-0/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC_FOR_XE)))
STATUS of the LISTENER

Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 18.0.0.0.0 - Production
Start Date                07-OCT-2022 17:05:34
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           XE
Listener Parameter File   /opt/oracle/product/18c/dbhomeXE/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/oracle-keycloak-int-0/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
ERROR:
ORA-12547: TNS:lost contact

SP2-0306: Invalid option.
Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
SP2-0306: Invalid option.
Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
SP2-0157: unable to CONNECT to ORACLE after 3 attempts, exiting SQL*Plus`

#############
#Log End######
#############

I guess the issue appears when "lsnrctl start" is executed in line 349 of the container-entrypoint.sh script.

It is not possible to know the user id, when building the image. It is a randomly assinged id on container startup in OpenShift.

**Comment by gvenzl** [comment]
It's certainly a territory that I haven't moved myself on yet so I cannot provide much insight into how much or if this works. What I do know is that the user starting the Oracle Database has to be in the `dba` group, that's the group that is linked to the `SYSDBA` system privilege.

I just managed to start up the database with a new user `test` that I have created and added to `dba`:

```
bash-4.4# useradd test
bash-4.4# id test
uid=54322(test) gid=54331(test) groups=54331(test)
bash-4.4# usermod -a -G dba test
bash-4.4# id test
uid=54322(test) gid=54331(test) groups=54331(test),54322(dba)
bash-4.4# chown -R test:test /opt/oracle
bash-4.4# chmod -R g+rwX /opt/oracle
```

```
[test@3e9adf69d463 oracle]$ id
uid=54322(test) gid=54331(test) groups=54331(test),54322(dba)
[test@3e9adf69d463 oracle]$ sqlplus / as sysdba

SQL*Plus: Release 21.0.0.0.0 - Production on Sun Oct 9 16:54:58 2022
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> startup;
ORACLE instance started.

Total System Global Area 1241512272 bytes
Fixed Size		    9685328 bytes
Variable Size		  318767104 bytes
Database Buffers	  905969664 bytes
Redo Buffers		    7090176 bytes
Database mounted.
Database opened.
SQL>
```

But again, how supported/wise this is, I do not know.

**Comment by gvenzl** [comment]
Hi @teceP,

As @mprins pointed out, XE can be used in production but it does have the outlined constraints that you should be aware of!

I'll close this question for now, if you have any more, feel free to open it again.

**Comment by teceP** [comment]
Thank you for investing your time!

What do you mean with outlined constraints?

**Comment by gvenzl** [comment]
What @mprins has said above, be aware that Oracle XE is unsupported: https://www.oracle.com/database/technologies/appdev/xe/faq.html#prod
