### ISSUE TITLE
Expose database port in Dockerfile

### ISSUE THREAD

**Issue by EmteZogaf** [gvenzl/oci-oracle-xe#148]
I would like to use this image as service in GitLab CI, but for this to work the image has to expose the ports by default via the [EXPOSE](https://docs.docker.com/engine/reference/builder/#expose) command in Dockerfile. See https://docs.gitlab.com/ee/ci/services/#how-the-health-check-of-services-works.

**Comment by gvenzl** [comment]
Hi @EmteZogaf,

Please use the `--port` command as explained [over here](https://github.com/gvenzl/oci-oracle-xe/pull/123#issuecomment-1277531209) in the excellent finding by @maacarbo who can perhaps also offer further help, if required.
