### ISSUE TITLE
REGULAR flavors have Spatial which requires Java (OJVM) feature

### ISSUE THREAD

**Issue by loiclefevre** [gvenzl/oci-oracle-xe#161]
It appears that the regular images have spatial features available but some of them require to have the JVM installed.

Example running a spatial test on a regular image without Java:
```
select id, ST_GEOMETRY(t.GEOM).ST_CONTAINS(ST_GEOMETRY.FROM_WKT(?, 4326)) as result from geomtest t
[ORA-29538: Java not installed
ORA-06512: at "MDSYS.SDO_JAVA_STP", line 82
ORA-06512: at "MDSYS.SDO_UTIL", line 7336
ORA-06512: at "MDSYS.ST_GEOMETRY", line 558
ORA-06512: at "MDSYS.ST_GEOMETRY", line 588
]
```

**Comment by gvenzl** [comment]
That is correct, some Spatial features do require OJVM while others do not, hence Spatial is still available in the regular image. If somebody requires OJVM, they need to use the full image as documented in https://github.com/gvenzl/oci-oracle-xe/blob/main/README.md#image-flavors and https://github.com/gvenzl/oci-oracle-xe/blob/main/ImageDetails.md
