### ISSUE TITLE
Permission Issue with M1 Mac OS and Colima

### ISSUE THREAD

**Issue by sselvia** [gvenzl/oci-oracle-xe#163]
I'm seeing permission issues with the images running on the M1 Mac, I've setup my Colima configuration to have write permission to the folder where I'm persisting the oracle data files.  This also leads to issues setting the password for the SYS and SYSTEM accounts.  If I don't use a persistence volume the container will be created, the passwords set, and start correctly.

- location: "/Users/fname.lname/database-files/oracle"
  writable: true

Colima startup command -> colima start --arch x86_64 --cpu 4 --memory 6 --kubernetes

Docker run command -> docker run -d --name ORACLE_XE -p 1521:1521 -p 5500:5500 -e ORACLE_PASSWORD=password123! -v /Users/fname.lname/database-files/oracle/startup:/opt/oracle/scripts/startup -v /Users/fname.lname/database-files/oracle:/opt/oracle/oradata gvenzl/oracle-xe:full

mv: failed to preserve ownership for '/opt/oracle/oradata/dbconfig/XE/spfileXE.ora': Permission denied
2022-12-03T15:15:14.618683000Z mv: failed to preserve ownership for '/opt/oracle/oradata/dbconfig/XE/orapwXE': Permission denied
2022-12-03T15:15:14.671194000Z mv: failed to preserve ownership for '/opt/oracle/oradata/dbconfig/XE/listener.ora': Permission denied
2022-12-03T15:15:14.722341000Z mv: failed to preserve ownership for '/opt/oracle/oradata/dbconfig/XE/tnsnames.ora': Permission denied
2022-12-03T15:15:14.777883000Z mv: failed to preserve ownership for '/opt/oracle/oradata/dbconfig/XE/sqlnet.ora': Permission denied

CONTAINER: Resetting SYS and SYSTEM passwords.
2022-12-03T15:16:06.286419000Z    ALTER USER SYS    IDENTIFIED BY "password123!"
2022-12-03T15:16:06.290912000Z *
2022-12-03T15:16:06.291040000Z ERROR at line 1:
2022-12-03T15:16:06.291075000Z ORA-01990: error opening password file ''

**Comment by vedanta28** [comment]
Were you able to install it on Mac M1?

**Comment by altitudedashboard** [comment]
> Were you able to install it on Mac M1?

It works just fine without shared volumes between the container and the host.
Another alternative I have found is using Windows 11 Pro arm64 running in (the free for personal use) VMware Fusion.
Windows 11 arm64 has an emulation layer for x86_64 to arm64 which is fas superior to qemu which is used by colima.
I am running Oracle 19c EE on Windows with acceptable performance.

**Comment by vedanta28** [comment]
@altitudedashboard I found an answer here https://stackoverflow.com/a/72537954/15384651. I followed the steps till the penultimate one. But, not sure which Oracle DB image I should install. We have been asked to install the [Oracle 21c ](https://www.oracle.com/in/database/technologies/xe-downloads.html)Express Edition for our Lab classes on Database systems. Should which of the images should I use for this? 

Or just running
`docker run -e ORACLE_RANDOM_PASSWORD=yes -p 1521:1521 -d gvenzl/oracle-xe`
works? 
Also, do you know if the Oracle Cloud DB would work? Does it provide the same functionalities, and is the interface close enough to the offline installation?

<img width="563" alt="image" src="https://user-images.githubusercontent.com/74861233/211167305-9de0e488-62e6-4e01-a03f-696cb31c2920.png">

**Comment by altitudedashboard** [comment]
docker run -d -p 1521:1521 -p 5500:5500 -e ORACLE_PASSWORD=PutAPasswordHere -v oradata:/opt/oracle/oradata:rw --name oraxe gvenzl/oracle-xe -full

should do the job

**Comment by vedanta28** [comment]
@altitudedashboard I tried the above instruction to check if it worked. 
<img width="820" alt="image" src="https://user-images.githubusercontent.com/74861233/211167840-88da3705-411b-4f93-a412-7135256425de.png">
After running, it showed as above. Do you think the installation worked? Could you suggest any method with which I can check that? I have SQL Developer on my Machine. Can you suggest anything to confirm if the installation worked? I am really new to Docker, and the Database stuffs, so not sure if I am doing things right.

**Comment by altitudedashboard** [comment]
Yes. Try:
docker logs -f <the long id, ideally you should have used a name>

**Comment by vedanta28** [comment]
I have the following output. I guess the installation worked? Also, whenever I want to use this (Oracle XE), should I use some command? 
<img width="854" alt="image" src="https://user-images.githubusercontent.com/74861233/211168073-b58007db-577d-4f51-8c0c-20bf1849d518.png">
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/74861233/211168090-15ee9a6d-b1a2-433b-8214-e6d714c62a2b.png">

**Comment by altitudedashboard** [comment]
Yes, it worked. You may connect using
`docker exec -ti <the long id> bash`
and you are inside the container. Next try:
`sqlplus / as sysdba`
And then you need to do some reading, this is not the place...
To log out use Ctrl+D

**Comment by vedanta28** [comment]
@altitudedashboard Thanks a ton 🙏. I never thought I would have installed it this easily.

**Comment by altitudedashboard** [comment]
This is the purpose of this image, to help developers get quickly an Oracle XE docker container

**Comment by vedanta28** [comment]
> It works just fine without shared volumes between the container and the host.

@altitudedashboard Also, one last thing. You mentioned this at the start of your answer. Could you clarify how much of an issue, or loss of functionality it will cause, as opposed to a standard installation (for users on an x86-64 Machine)?

**Comment by altitudedashboard** [comment]
As it seems you are only now starting it will not impact you at all as you don't need this feature
