### ISSUE TITLE
DBMS_JAVA and DBA_JAVA_POLICY

### ISSUE THREAD

**Issue by alourie** [gvenzl/oci-oracle-xe#167]
I see that the installation script is specifically removing Java-related packages. Is there an alternative for the `dba_java_policy` view? We're importing data from a 3rd party which creates the following:
```
CREATE TABLE TEMP_JAVA_PRIVS AS SELECT KIND, GRANTEE, TYPE_SCHEMA, TYPE_NAME, NAME, ACTION, ENABLED FROM SYS.DBA_JAVA_POLICY WHERE ROWNUM > 1;
```

However, it fails as the mentioned doesn't exist.

Thanks!

**Comment by mprins** [comment]
use the `-full` image?

**Comment by alourie** [comment]
Yep, that works, thanks!
