### ISSUE TITLE
Allow mounting external volume for oradata subfolders

### ISSUE THREAD

**Issue by loiclefevre** [gvenzl/oci-oracle-xe#171]
As _non-faststart_ images are created today, datafiles are being zipped and the content under `/opt/oracle/oradata` is finally deleted after building the zip archive.

Because of the delete, one can't mount an external volume say solely for XEPDB1 pluggable database.

Adding these lines to `install.2130.sh` would solve this issue:
```
...
chown oracle:dba "${ORACLE_SID}".zip
 mv "${ORACLE_SID}".zip "${ORACLE_BASE}"/
 rm  -r "${ORACLE_SID}"
+# Recreate PDB folder for eventual external mount point!
+mkdir -p "${ORACLE_SID}"/XEPDB1
+chown -R oracle:dba "${ORACLE_SID}"
 cd - 1> /dev/null
...
```

**Comment by loiclefevre** [comment]
PR #172 created

**Comment by gvenzl** [comment]
Merged.
