### ISSUE TITLE
Init script log location

### ISSUE THREAD

**Issue by Modulariti** [gvenzl/oci-oracle-xe#173]
Hi,

I need some logs to check whether the SQL scripts I put in /container-entrypoint-initdb.d are successfully executed/not. Where can I find these logs ?

Regards.

**Comment by gvenzl** [comment]
Hi @Modulariti,

Thanks a lot for using these images!

The output of the init scripts is directly printed into the container log itself.

Look for 

```
CONTAINER: Executing user defined scripts...
```

and

```
CONTAINER: DONE: Executing user defined scripts.
```

The output of your scripts will be in between those two lines.
