### ISSUE TITLE
Question: How to extend 'gvenzl/oracle-xe' with custom 'initdb' folder and execute?

### ISSUE THREAD

**Issue by emeraldjava** [gvenzl/oci-oracle-xe#176]
Hi,

I have a scenario where I want to create a custom docker image which extends 'gvenzl/oracle-xe' and run a specific set of initdb and startdb scripts. I appreciate this can be done in a simpler manner with 'docker-compose' but in this case we expect the initdb scripts to change in future.

Once this base image is created we could tag it, and config it via 'docker-compose' where only the DB detail and PASSWORD are provided.

My folder structure is shown below with folders for the initdb and startdb files.

    initdb/001_abc.sql
    startdb/002_script.sh
    Dockerfile

My Dockerfile then runs these 4 steps

`
// https://hub.docker.com/r/gvenzl/oracle-xe
// step 1 - start with the base image
FROM gvenzl/oracle-xe:21-full

// step 2 - copy my local sql files to the container
COPY ./initdb/* /container-entrypoint-initdb.d/

// step 3 - copy local start scripts files to the container
COPY ./startdb/* /container-entrypoint-startdb.d/

// step 4 - run the base image
RUN exec container-entrypoint.sh
`

I'm getting this error and am unclear if my step 4 is correct.

Sending build context to Docker daemon   5.12kB
Step 1/4 : FROM gvenzl/oracle-xe:21-full
 ---> f42510c237d9
Step 2/4 : COPY ./initdb/* /container-entrypoint-initdb.d/
 ---> Using cache
 ---> 2bb0221331ea
Step 3/4 : COPY ./startdb/* /container-entrypoint-startdb.d/
 ---> Using cache
 ---> 9c95ca448011
Step 4/4 : RUN exec container-entrypoint.sh
 ---> Running in 2ebe0fc741df
CONTAINER: starting up...
Oracle Database SYS and SYSTEM passwords have to be specified at first database startup.
Please specify a password either via the $ORACLE_PASSWORD variable, e.g. '-e ORACLE_PASSWORD=<password>'
or set the $ORACLE_RANDOM_PASSWORD environment variable to any value, e.g. '-e ORACLE_RANDOM_PASSWORD=yes'.
The command '/bin/sh -c exec container-entrypoint.sh' returned a non-zero code: 1

And is there a suggestion on how i can pass the ORACLE_PASSWORD value as a parameter? Any advise would be appreciated.

**Comment by KyleAure** [comment]
Question 1:  The command '/bin/sh -c exec container-entrypoint.sh' returned a non-zero code: 1
Did you make sure that `container-entrypoint.sh` is executable? 
Try adding `RUN chmod -R +x /container-entrypoint-initdb.d/` 

Question 2: Oracle Database SYS and SYSTEM passwords have to be specified at first database startup.
Try adding `ENV ORACLE_PASSWORD=<your-secret-password>` to your dockerfile.

**Comment by emeraldjava** [comment]
Thanks - it runs now with this Dockerfile config

FROM gvenzl/oracle-xe:21-full

ENV ORACLE_PASSWORD="xxx" \
    APP_USER="MYDB" \
    APP_USER_PASSWORD="xxx"

# step 2 - copy my local sql files to the container
COPY ./initdb/* /container-entrypoint-initdb.d/

# step 3 - copy local start scripts files to the container
COPY ./startdb/* /container-entrypoint-startdb.d/

# step 4 - run the base image
USER oracle
WORKDIR ${ORACLE_BASE}
ENTRYPOINT ["container-entrypoint.sh"]

Still facing an issue to connect - but progress.

**Comment by emeraldjava** [comment]
Sorry - i should move this to discussion.
