### ISSUE TITLE
Update 21c images with Critical Patch updates from Jan 2023

### ISSUE THREAD

**Issue by KyleAure** [gvenzl/oci-oracle-xe#177]
The January security patch update was released here: 
https://www.oracle.com/security-alerts/cpujan2023.html#AppendixDB

Can the 21c base images be updated to pull a new version that has these patches and the faststart images be updated to have the patches already installed?

**Comment by mprins** [comment]
AFAIK Oracle patches require a support contract, but XE editions are unsupported... hence this could only be done when Oracle provides (new) downloads, current downloads are from September 08, 2021, https://www.oracle.com/nl/database/technologies/xe-downloads.html

**Comment by gvenzl** [comment]
That is correct, [Oracle doesn't provide any support or patches for Express Edition](https://www.oracle.com/database/technologies/appdev/xe/faq.html#patches):

> How can I get support?
> Go to the [Oracle Database Express Edition (XE) Forum](https://community.oracle.com/tech/developers/categories/oracle_database_express_edition_xe), and search existing questions and answers, or enter your own question.
> 
> Can I log an SR against XE?
> No, you can only log Service Requests, with Oracle Support, against fully supported products, such as Oracle Database Enterprise Edition, Oracle Database Standard Edition 2, and all of the Oracle Database Cloud Services.
> 
> Will patches be provided for Oracle Database XE?
> No, patches will not be released for XE. To obtain patches you must be on a fully supported edition, such as Oracle Database Enterprise Edition or Oracle Database Standard Edition 2.
