### ISSUE TITLE
container-entrypoint-initdb.d sql

### ISSUE THREAD

**Issue by kaihendry** [gvenzl/oci-oracle-xe#178]
Would be nice to show how to please get data out of an existing database into container-entrypoint-initdb.d/*.sql files.

I'm mounting `oradata:/opt/oracle/oradata` and instead of opaque .dbf files, I want .sql to work with.

I think the steps are something like:

1. docker exec oracle expdp SYSTEM/$(PASSWORD)@XE dumpfile=export.dmp logfile=export.log
2. docker exec oracle impdp dumpfile=export.dmp sqlfile=export.sql

Though it would be good if you could please confirm since it doesn't quite work for me:

```
docker exec oracle expdp SYSTEM/letmein@XE dumpfile=export.dmp logfile=export.log

Export: Release 21.0.0.0.0 - Production on Thu Jan 26 09:00:02 2023
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle and/or its affiliates.  All rights reserved.

Connected to: Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
ORA-39001: invalid argument value
ORA-39000: bad dump file specification
ORA-31641: unable to create dump file "/opt/oracle/admin/XE/dpdump/export.dmp"
ORA-27038: created file already exists
Additional information: 1


make: *** [export] Error 1

❯ make dmp2sql
docker exec oracle impdp dumpfile=export.dmp sqlfile=ddl.sql

Import: Release 21.0.0.0.0 - Production on Thu Jan 26 09:00:38 2023
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle and/or its affiliates.  All rights reserved.

Username: UDI-00005: unexpected End-Of-File encountered while reading input.

```

My goal is to establish a test database that quickly stands up in a CI/CD pipeline for a test suite to be run. Any other tips to get this going would be great. I think I need your "slim-faststart" images right?

**Comment by gvenzl** [comment]
Hi @kaihendry,

Thanks for using these images!

The container doesn't provide any built-in functionality to extract data from a database, that's left to the user to decide how, where and in what format.

However, there are multiple ways to unload data from an Oracle Database, export & import being one of them.
If you just want SQL scripts, the best way is probably using Oracle's SQLcl command-line tool and the `UNLOAD` command.

I'm curious though, in what scenarios would you have data in the database that hasn't been first inserted via setup/init scripts or similar given that these images provide an empty database (aside from the Oracle Database internal data dictionary, etc)? Why the need to extract data from the database, could you elaborate more, please? I'd like to understand the process that you have in mind.

Yes, generally speaking the `*-faststart` images are the best for CI/CD environments as they already have an uncompressed, ready-to-go database and are hence faster to start up.

**Comment by kaihendry** [comment]
Hi! I've put my reasoning upon https://stackoverflow.com/questions/75332894/

> The goal is to export an existing test Oracle database to SQL so that it can be run in a test pipeline using a Docker images's /container-entrypoint-initdb.d bootstrap. Currently we mount an oradata export, but it's opaque what the actual data is, hence the desire to use SQL so that it can be maintained via git.

The SQLcl command appears unpackaged In your Docker image or anywhere else, do you have any suggestions there? Ideally want to script this.

The scenario I guess is that is that it's a legacy project that never started using a testing database bootstrapped from setup/init scripts.

Thank you!

**Comment by gvenzl** [comment]
Hi @kaihendry,

Ah yes, thanks for that additional explanation!

The only tooling from Oracle that allows you to unload DDL and data into SQL statements is SQL Developer and SQLcl (both use the same common core).
Other third-party tools may provide similar functionality and might be a better fit for what you are looking for.

If you want SQL statements, your best bet from an official Oracle tooling aspect is SQLcl, however, be aware that its `UNLOAD` functionality is table-based, i.e. you have to run it table by table.

SQLcl is indeed not packaged with my images as it is a standalone Java-based command-line utility. However, you can either just pull it from the web as part of the pipeline (https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip) (Note, it requires Java 11 or up to run) or pull it as a separate container from [`container-registry.oracle.com/database/sqlcl:latest`](https://container-registry.oracle.com/) and add it to the same network as the database container in order for it to connect.

Note, SQLcl also has built-in Liquibase support (`lb` command) that can generate a changelog of the current state of the database. I don't know too much about Liquibase but it may be another way to get to SQL statements, see https://docs.liquibase.com/workflows/liquibase-community/updating-the-database.html

Hope this helps!

**Comment by kaihendry** [comment]
```
docker pull container-registry.oracle.com/database/sqlcl:latest
Error response from daemon: Get "https://container-registry.oracle.com/v2/": x509: certificate signed by unknown authority
```

Does one need a user/pass to pull that sqlcl image btw?

-----

I'm hoping to show the flow from your install.sql -> export.sql here: https://github.com/kaihendry/oracle-sql
Guess my aim is to track any differences between export and import SQL. 😬

**Comment by gvenzl** [comment]
No, no user/pass is needed. 
It pulls fine for me:

```
$ podman pull container-registry.oracle.com/database/sqlcl:latest
Trying to pull container-registry.oracle.com/database/sqlcl:latest...
Getting image source signatures
Copying blob b316fdf08e1d done
Copying blob d26998a7c52d done
Copying blob 547ce718d15e done
Copying blob c07ee00b160d done
Copying config aa5931f47c done
Writing manifest to image destination
Storing signatures
aa5931f47c27e387adc5c912851ac65684f48641851c34592516e5247932d613
```

I wonder whether my setup ignored certificate issues, a quick google just pointed me to this, perhaps it helps: https://stackoverflow.com/questions/50768317/docker-pull-certificate-signed-by-unknown-authority

Oh nice, thanks for using that sample data too!

Hm, how will you ignore/detect a difference in the position of a given SQL statement?

**Comment by kaihendry** [comment]
Tbh I have no idea how I can tell there is a difference between the export/import SQL. The exported SQL is bound to be very different based on my experiments with **Oracle SQL Developer Export Wizard**.

I wonder how AWS DMS/SCT knows they've actually synced the data or not. Databases seem really hard to sync compared to an S3 blob!!

**Comment by gvenzl** [comment]
Yes, the exported SQL will include storage and other logically unrelated properties to the data and data model structure.

**Comment by kaihendry** [comment]
Are there some tools to clean up the produced SQL? 

Want to avoid any noise for bootstrapping this oracle test container 😬

**Comment by gvenzl** [comment]
Not sure about cleanup, but I'd check out Liquibase and its SQL mode. Given that it is a DDL change-tracking tool, it might have what you need.

**Comment by akridge** [comment]
Just in case it can be helpful, I had to do something similar the other day using SQLcl. If you just need DDL and SQL inserts, here is our quick and dirty code. Its per table tho:
----cmd----
```
sql.exe username/password@localhost:1521/XEPDB1 @C:\location_of_sql_file\export_data_as_sql_inserts_script.sql
```
---- export_data_as_sql_inserts_script.sql ----
```
SET PAGESIZE #HERE
SET LINESIZE  #HERE
SET HEADING OFF
SET TRIMSPOOL ON
SET TERMOUT OFF

SET SQLFORMAT insert

SPOOL C:\ddl_backup_location\01_table_name_ddl.sql
ddl table_name
SPOOL OFF

SPOOL C:\data_backup_location\01_table_name_data.sql
SELECT * FROM table_name
SPOOL OFF

exit
```
Can of course turn on and off different things to get intended output.

**Comment by kaihendry** [comment]
Thanks @akridge .. I actually do something like that already https://github.com/kaihendry/oracle-sql/blob/main/unload.sh

Though indeed it suffers from issues like being per table and it feels unstable on large tables.

Thanks to @gvenzl there is a workaround for the table by table restore if you disable key constraints and add it back in later. :sweat: https://dabase.com/blog/2023/oracle/#there-is-no-oracle-dump
