### ISSUE TITLE
Create Docker Image for 19c

### ISSUE THREAD

**Issue by mustaphazorgati** [gvenzl/oci-oracle-xe#181]
Hey @gvenzl!

Is is possible to provide a Docker Image for the version 19c (19.3). This would be amazing since our docker image used for testing (through testcontainers) would be aligned to our production environment :)

If you need any assistence, let me know

**Comment by mprins** [comment]
There is no 19.3 XE edition; license restrictions prevent distributing non-XE versions. 
Please use the official Oracle recipes at https://github.com/oracle/docker-images to build and distribute your own, private image

**Comment by gvenzl** [comment]
Thanks a lot for answering this question, @mprins.

Indeed, Oracle never released a 19c XE version, see https://www.oracle.com/database/technologies/xe-downloads.html for reference.
