### ISSUE TITLE
How does one use sqlplus version 18 without spawning an Oracle instance?

### ISSUE THREAD

**Issue by kaihendry** [gvenzl/oci-oracle-xe#184]
I expected something like:

    docker run --rm --link oracle -it -e ORACLE_PASSWORD=foo gvenzl/oracle-xe:18-full --entrypoint sqlplus 

To work, but instead it boots the database ... `CONTAINER: first database startup, initializing... `

I'm looking for an easy way to refer version 18 (for example) of Oracle tools like sqlplus or sqlcl.

Sidenote: I have no idea how to find the tags of **container-registry.oracle.com/database/sqlcl**

**Comment by gvenzl** [comment]
`--entrypoint` needs to be before the image name, see the [Docker run reference](https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime)

This works:

```
$ docker run -it -e ORACLE_PASSWORD=foo --entrypoint sqlplus gvenzl/oracle-xe:21-slim-faststart

SQL*Plus: Release 21.0.0.0.0 - Production on Tue Feb 7 15:46:58 2023
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle.  All rights reserved.

Enter user-name:
```

While here the `--entrypoint` option is ignored by Docker:

```
$ docker run -it -e ORACLE_PASSWORD=foo gvenzl/oracle-xe:21-slim-faststart --entrypoint sqlplus
CONTAINER: starting up...
CONTAINER: first database startup, initializing...
CONTAINER: starting up Oracle Database...
```

**Comment by kaihendry** [comment]
Thank you!

RE container-registry.oracle.com/database/sqlcl there appears to be only a limited amount of tags:

```
latest	linux/amd64	432.3 MB	docker pull container-registry-osaka.oracle.com/database/sqlcl:latest	2 months ago	aa5931f47c27
latest	linux/arm64	425.39 MB	docker pull container-registry-osaka.oracle.com/database/sqlcl:latest	2 months ago	fafe840534db
22.4.0	linux/amd64	432.3 MB	docker pull container-registry-osaka.oracle.com/database/sqlcl:22.4.0	2 months ago	aa5931f47c27
22.4.0	linux/arm64	425.39 MB	docker pull container-registry-osaka.oracle.com/database/sqlcl:22.4.0	2 months ago	fafe840534db
22.3.1	linux/amd64	428.16 MB	docker pull container-registry-osaka.oracle.com/database/sqlcl:22.3.1	4 months ago	e2a8e9716b92
22.2.0	linux/amd64	428.89 MB	docker pull container-registry-osaka.oracle.com/database/sqlcl:22.2.0	7 months ago	168e047c4981
22.1.1	linux/amd64	427.33 MB	docker pull container-registry-osaka.oracle.com/database/sqlcl:22.1.1	8 months ago	0c616f40d330
```

I.e. 18.4 not packaged https://docs.oracle.com/en/database/oracle/sql-developer/18.4/sqcqr/
