### ISSUE TITLE
Add details for enabling In-Memory Columnar processing on XE

### ISSUE THREAD

**Issue by loiclefevre** [gvenzl/oci-oracle-xe#188]
This [blog post](https://blogs.oracle.com/coretec/post/oracle-database-in-memory---getting-started-with-oracle-database-21-xe-and-sql-developer) presents a memory setup to enable In-Memory Columnar processing (SIMD vectorized CPU instructions...) with XE:

```sql
-- Connect to CDB as DBA
connect / as sysdba 
-- Edit following init.ora parameters
alter system set sga_target=1568M scope=spfile; 
alter system set pga_aggregate_target=412M scope=spfile; 
alter system set inmemory_size=1G scope=spfile; 
shutdown immediate; 
startup;
```

It would be worth highlighting this inside the image documentation.

**Comment by gvenzl** [comment]
Merged
