### ISSUE TITLE
Is installing drivers like JDBC and linking them with our database possible in M1 Mac?

### ISSUE THREAD

**Issue by vedanta28** [gvenzl/oci-oracle-xe#192]
I used the instructions mentioned in this repo to install the Oracle database in my system. Now, I would like to know if installing JDBC drivers is possible. I was following [this guide](https://docs.oracle.com/cd/E11882_01/appdev.112/e12137/getstart.htm#TDPJD113) for the installation. But, there are several steps I am not able to follow through. In the blog, they mentioned ORACLE_HOME directory and asked to check for certain files there. But, I am not sure where this directory is located in my system. I used colima and docker to install the database.

**Comment by gvenzl** [comment]
Hey @vedanta28, thanks a lot for using these images!

JDBC is a thin driver and entirely Java-based so it should work just fine on Mac M1.
You can get the latest JDBC drivers straight from [Maven Central](https://central.sonatype.com/artifact/com.oracle.database.jdbc/ojdbc11/21.9.0.0).

I hope this answers your question.

Thanks,

**Comment by vedanta28** [comment]
@gvenzl Thanks. It worked.
