### ISSUE TITLE
Use 7z compression as well as 7z self-extracting archive

### ISSUE THREAD

**Issue by loiclefevre** [gvenzl/oci-oracle-xe#193]
7-Zip provides a very efficient compression algorithm (LZMA) which improves further database file compression.
It also provides self-extracting archive capabilities which avoid installing unzip and gzip.
Finally, decompression can use multiple threads for even faster start time!

**Comment by gvenzl** [comment]
Implemented and released. Thanks a lot for this ER, @loiclefevre! :)
