### ISSUE TITLE
[Question] Is "fast-start" meant for snapshotting user-included DB's?

### ISSUE THREAD

**Issue by GavinRay97** [gvenzl/oci-oracle-xe#196]
We have a scenario at work where we're trying to set up a fast setup/teardown cycle of Oracle test containers

We want to seed this container with a starting database and seed data. There is this `fast-start` image, and I'm curious whether this is tailored for this use-case and if so, how exactly it works?

Thank you =)

**Comment by gvenzl** [comment]
Hi @GavinRay97,

Thanks a lot for using these images!

The `faststart` images yield a faster overall container startup time by including uncompressed Oracle Database data files inside the image (hence making the overall image size larger).

It sounds like what you are after is to have an image that not only already has a database ready to go inside it, but also that the database already has been seeded with the right starter set, correct?

There are multiple ways to approach this.

1) The approach that will yield you the fastest possible startup time would be to extend the `faststart` image by running the [Initialization scripts](https://github.com/gvenzl/oci-oracle-xe#initialization-scripts) facilities to produce a new image with your seeded database.

1) Another approach would be to specify a volume, seed your database once, save that volume somewhere and attach a cloned volume whenever you want to start up a new container. That's going to be slower unless you have copy-on-write storage available for the volume.

1) Lastly if your setup scripts don't take very long, you can just use said initialization scripts facility with the already existing images and be done with it.
