### ISSUE TITLE
Unable to start container on M1 using Colima

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [gvenzl/oci-oracle-xe#200]
I have tried to follow the [instructions](https://github.com/gvenzl/oci-oracle-xe#oracle-xe-on-apple-m-chips) for running the image on M1:

1. Install colima ([instructions](https://github.com/abiosoft/colima#installation))
2. Run colima start --arch x86_64 --memory 4
3. Start container as usual

When I run `colima list` I get the following output:
```
PROFILE    STATUS     ARCH      CPUS    MEMORY    DISK     RUNTIME    ADDRESS
default    Running    x86_64    2       4GiB      60GiB    docker     
```

I start the container:
```
docker run -d --name oracle_db \
-p 1521:1521 \
-e ORACLE_RANDOM_PASSWORD="y" \
-e APP_USER="my_user" \
-e APP_USER_PASSWORD="my_password_which_I_really_should_change" \
gvenzl/oracle-xe
```
However the container exits after about 1 minute:
```
CONTAINER ID   IMAGE              COMMAND                  CREATED         STATUS                        PORTS     NAMES
90bbe2eb18a7   gvenzl/oracle-xe   "container-entrypoin…"   2 minutes ago   Exited (204) 36 seconds ago             oracle_db
```

Any thoughts?

**Comment by gvenzl** [comment]
Hi @SoumayaMauthoorMOJ,

Thanks a lot for using these images!

Unfortunately, I myself do not run on a Mac M1 and can hence only provide limited insights.
Hopefully, other folks in the community here can add their experiences.

Could you please provide the log from the container via `docker logs oracle-db`?

**Comment by SoumayaMauthoorMOJ** [comment]
Thanks @gvenzl all sorted now I used `docker logs` and the password was too long for some reason:

```
############################################
ORACLE PASSWORD FOR SYS AND SYSTEM: ZTM4MjMx
############################################

Session altered.

   CREATE USER my_user IDENTIFIED BY "my_password_which_I_really_should_change" QUOTA UNLIMITED ON USERS
                                     *
ERROR at line 1:
ORA-00972: identifier is too long
```
