### ISSUE TITLE
Unable to find XE.zip while using the Dockerfile.faststart

### ISSUE THREAD

**Issue by thomaskaviani** [gvenzl/oci-oracle-xe#205]
I had a project running that pulled the faststart image. But since the recent update of the images I'm unable to use it anymore. 
I tried to use the dockerfile from your github to see if something in the custom file from our project could be the issue. But I found out that I'm also unable to get that one working.

The dockerfile i'm trying this with (from your github), i filled in a base image I actually want to use and removed all comments here for readability: 

```
ARG BASE_IMAGE

FROM gvenzl/oracle-xe:21.3.0-slim-faststart as base

FROM base as cdb_pdb_seed

RUN unzip "${ORACLE_BASE}"/"${ORACLE_SID}".zip -x XE/system*.dbf XE/sysaux*.dbf -d "${ORACLE_BASE}"/oradata/ 1> /dev/null
RUN rm XE.zip

FROM cdb_pdb_seed as cdb_sysaux

COPY --from=base "${ORACLE_BASE}"/"${ORACLE_SID}".zip "${ORACLE_BASE}"/"${ORACLE_SID}".zip

RUN unzip "${ORACLE_BASE}"/"${ORACLE_SID}".zip XE/sysaux*.dbf -d "${ORACLE_BASE}"/oradata/ 1> /dev/null
RUN rm XE.zip

FROM cdb_sysaux as cdb_system

COPY --from=base "${ORACLE_BASE}"/"${ORACLE_SID}".zip "${ORACLE_BASE}"/"${ORACLE_SID}".zip

RUN unzip "${ORACLE_BASE}"/"${ORACLE_SID}".zip XE/system*.dbf -d "${ORACLE_BASE}"/oradata/ 1> /dev/null
RUN rm XE.zip
```

I then try to build the image on my machine with the following command: 

`docker build -t"test-oracle-xe" .`

It starts downloading and extracting but runs into issues on the following part:
```#4 extracting sha256:d93359e16473a9367793da782c174ffb9f2bdb54831fc9134c812303676d6c73 7.9s done
#4 extracting sha256:a3ee768b83c9208a3e3eb57c256585a81e4ade4da2cf01f8950d28824e6a58cd
#4 extracting sha256:a3ee768b83c9208a3e3eb57c256585a81e4ade4da2cf01f8950d28824e6a58cd 5.1s
#4 extracting sha256:a3ee768b83c9208a3e3eb57c256585a81e4ade4da2cf01f8950d28824e6a58cd 10.0s done
#4 DONE 208.3s

#5 [cdb_pdb_seed 1/2] RUN unzip "/opt/oracle"/"XE".zip -x XE/system*.dbf XE/sysaux*.dbf -d "/opt/oracle"/oradata/ 1> /dev/null
#5 sha256:7dde05426a8310384834af43f8945c04bdc7862ce7d7a08278bc82c4c0663508
#5 CACHED

#6 [cdb_pdb_seed 2/2] RUN rm XE.zip
#6 sha256:5a964e7af7bd6c98e0f55ca91dd45a218a27f7272dd938b09483287fbf79e2f0
#6 CACHED

#7 [cdb_sysaux 1/3] COPY --from=base /opt/oracle/XE.zip /opt/oracle/XE.zip
#7 sha256:e1832ad8448f2aa563f51f84c1273e813d7eea61c98fdac63a2798bab9428138
#7 ERROR: "/opt/oracle/XE.zip" not found: not found

#8 [cdb_sysaux 2/3] RUN unzip "/opt/oracle"/"XE".zip XE/sysaux*.dbf -d "/opt/oracle"/oradata/ 1> /dev/null
#8 sha256:ee2ceacd81305581cad4a5586df3d680e6ede708e4726eaa0e205758874be2e9
#8 CACHED

#9 [cdb_sysaux 3/3] RUN rm XE.zip
#9 sha256:e5ee9cae6c297628b03fc30a1104de996fb3b4ad4b2409656c75824d80be7cf7
#9 CACHED

#10 [cdb_system 1/3] COPY --from=base /opt/oracle/XE.zip /opt/oracle/XE.zip
#10 sha256:4187d26509513848e755cd13d2021bc09edcba3fa820f8c84920e9bf1e69ac1f
#10 ERROR: "/opt/oracle/XE.zip" not found: not found

#5 [cdb_pdb_seed 1/2] RUN unzip "/opt/oracle"/"XE".zip -x XE/system*.dbf XE/sysaux*.dbf -d "/opt/oracle"/oradata/ 1> /dev/null
#5 sha256:7dde05426a8310384834af43f8945c04bdc7862ce7d7a08278bc82c4c0663508
#5 CANCELED
------
 > [cdb_sysaux 1/3] COPY --from=base /opt/oracle/XE.zip /opt/oracle/XE.zip:
------
------
 > [cdb_system 1/3] COPY --from=base /opt/oracle/XE.zip /opt/oracle/XE.zip:
------
failed to compute cache key: "/opt/oracle/XE.zip" not found: not found
```

Is there something I am missing, or could there be an issue with the dockerfile or image?

**Comment by gvenzl** [comment]
My apologies, @thomaskaviani!

An experimental feature has sneaked its way into last weekend's image upload.
I have reverted the images to the backup from a couple of weeks ago, your Dockerfile should work again as expected.

We are thinking about replacing the `zip` file and zip/unzip routines with 7z, which provides a better compression ratio and faster uncompression times.
Hence the file in the image `${ORACLE_SID}.zip` no longer existed but instead was called `${ORACLE_SID}.7z` (and `unzip` would not have been able to unzip the file).
Although we are still testing the feature, preliminary tests have shown great results in overall container startup times, so we will likely roll this out eventually.

**Comment by thomaskaviani** [comment]
Thank you for the fast response, the Dockerfile indeed works as expected. 

Your image I started using a few months back already improved jenkins build times by a lot, so I can't thank you enough for producing these.

nonetheless I look forward to the rollout of the new images with even better startup times.

**Comment by gvenzl** [comment]
That is great to hear, thank you very much!

If you like, please consider filing an issue or PR to add your project to https://github.com/gvenzl/oci-oracle-xe#users-of-these-images

**Comment by thomaskaviani** [comment]
I will discuss it with the owner of the project. It's an internal application of a company, so I'm not sure if they want it referenced online. But your name is on every file used and I'm actively promoting your images for all projects here that want to use Docker.

**Comment by gvenzl** [comment]
Hey @thomaskaviani,

No worries at all, and thanks a lot for promoting these images! :)

Btw, we rolled out that `7z` feature overnight.

You will have to change your unzip/zip instructions in your derived image.

See [here for unzip](https://github.com/gvenzl/oci-oracle-xe/blob/main/container-entrypoint.sh#L137) and [here for zip](https://github.com/gvenzl/oci-oracle-xe/blob/main/install.2130.sh#L1920).

The user's guide comes with the actual 7z download, which you can find [here](https://www.7-zip.org/download.html). But in short, `a` is for archive, `x` is for extract
