### ISSUE TITLE
ORA-65040: operation not allowed from within a pluggable database

### ISSUE THREAD

**Issue by indiVar0508** [gvenzl/oci-oracle-xe#206]
Hi , 

I am using `gvenzl/oracle-xe:latest` image to do developer testing for my codebase,
here is my docker command that i am using
```
docker run -d -p 1521:1521 -e ORACLE_DATABASE=testing_db -e APP_USER=user1 -e APP_USER_PASSWORD=my_password -e ORACLE_RANDOM_PASSWORD=true --health-cmd healthcheck.sh gvenzl/oracle-xe
```

i have a testcase where i have to drop entire DB but i get this error
```
ORA-65040: operation not allowed from within a pluggable database
```
is there a way to address this issue?, like grant `user1` drop privilege? if it can be done + if it's applicable for pluggable DB(s)?

i eventually also want to use https://github.com/gvenzl/setup-oracle-free for my CI i see it has ability to give scripts so where i can grant this user drop privilege

can you help me address this issue i am not much aware of DB(s) not sure if drop privilege exists for oracle pluggable DB(s)?.

thanks!

**Comment by indiVar0508** [comment]
Hi @gvenzl , 

do you have any inputs for this one to point me in right direction

**Comment by gvenzl** [comment]
Hey @indiVar0508,

First of all, thanks for using these images!

It will depend on what your test case for dropping the entire DB looks like.
Yes, with pluggable databases you cannot drop a pluggable database with the `DROP DATABASE` command:

```
SQL> alter session set container = xepdb1;

Session altered.

SQL> drop database;
drop database
*
ERROR at line 1:
ORA-65040: operation not allowed from within a pluggable database
```

If you want to drop the PDB, you have to use [`DROP PLUGGABLE DATABASE`](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/DROP-PLUGGABLE-DATABASE.html).

Also check out the [Multitenant Admin Guide](https://docs.oracle.com/en/database/oracle/oracle-database/23/multi/removing-a-pdb.html#GUID-AE0FC673-3D8C-417E-B671-B2CE465E8DC3) for more info.

**Comment by indiVar0508** [comment]
Thanks @gvenzl ,
Closing this ticket able to make it work now!

**Comment by gvenzl** [comment]
Glad to hear that! :)
