### ISSUE TITLE
how to set DISK_ASYNCH_IO=FALSE before startup?

### ISSUE THREAD

**Issue by mysteryboy2000** [gvenzl/oci-oracle-xe#211]
I found a significant speed up on my docker container if I do below change.
ALTER SYSTEM SET DISK_ASYNCH_IO=FALSE SCOPE=SPFILE SID='*';

I make this change in the init.sql in /container-entrypoint-initdb.d/ but it looks like it will not take effect after the first container startup. it required a restart.

how to simply make the changes in the init.sql soon take effect ? thanks.

**Comment by gvenzl** [comment]
Hey @mysteryboy2000,

That's an interesting observation, could you share a bit more about the details of your environment and where you are running these containers?

As to setting this parameter to `false`, yes, the database requires a restart as per the [Oracle Database documentation](https://docs.oracle.com/en/database/oracle/oracle-database/23/refrn/DISK_ASYNCH_IO.html).

If you want an image that has a database already set with that parameter to `false` you would have to extend the image, set the parameter to false, and save that as a new image.
