### ISSUE TITLE
CVEs with current latest image

### ISSUE THREAD

**Issue by vab2048** [gvenzl/oci-oracle-xe#214]
Hello,

When I try and procure an image from docker hub into my company's internal container registry ( e.g. docker pull gvenzl/oracle-xe) my internal company software rejects it as it says there are currently CVEs:

- RHSA-2023:3018
- RHSA-2023:3106
- RHSA-2023:2963

Could you please do an updated release (which hopefully will not contain these CVEs).

Thanks

**Comment by gvenzl** [comment]
Hi @vab2048,

Thanks for using these images!

Image updates are due soon which, indeed, will hopefully fix these, although I cannot provide any guarantees as it's purely down to whether they have been fixed in the underlying OS image layer I'm using.

Thanks,

**Comment by gvenzl** [comment]
Images have been updated overnight.
