### ISSUE TITLE
healthcheck.sh does not check if pluggable database is available

### ISSUE THREAD

**Issue by nkruizinga** [gvenzl/oci-oracle-xe#215]
The current implementation of the healthcheck does not check if the pluggable db is available,  which makes it unusable for my use-case, which is using it as a health check in a Docker compose file. If I use this existing check, my application container starts too soon and will fail because it cannot reach the database.

If I change the health check to this:

```
db_status=$(sqlplus -s / << EOF
   set heading off;
   set pagesize 0;
   conn system/manager@localhost/XEPDB1;
   select 1 from dual;
   exit;
EOF
)
```

then everything works as I would expect it to.

Not sure if there is something I am missing, but it seems to me the existing health check is not what it should be.

Please note that I do not know if my solution is in anyway elegant (I expect not), I just found something that works.

**Comment by gvenzl** [comment]
Hi @nkruizinga,

Thanks for reporting this!

Indeed, the current healthcheck only checks the state of the database instance itself, which isn't very useful when somebody wants to see whether they can connect to the actual database.

We already fixed that in the successor images `gvenzl/oracle-free`, see https://github.com/gvenzl/oci-oracle-free/blob/main/healthcheck.sh

This can easily be backported to the `gvenzl/oracle-xe` images, will take a stab at it.

Meanwhile, I recommend upgrading to `gvenzl/oracle-free`.

Thanks,

**Comment by nkruizinga** [comment]
Hi. Thanks for looking into this! I can confirm the fix works for my case.

**Comment by gvenzl** [comment]
Awesome, thanks a lot for confirming, @nkruizinga!
