### ISSUE TITLE
Document Health-Check usage for GitHub Actions

### ISSUE THREAD

**Issue by gvenzl** [gvenzl/oci-oracle-xe#22]
After spending some time and the amazing help from @filiphr (issue #19), it is clear that setting up GitHub actions with the image can be challenging for users.
Instead of them getting frustrated, the documentation should provide the necessary steps to use these images here with GitHub Actions.

**Comment by gvenzl** [comment]
And not implemented and already live over at https://hub.docker.com/r/gvenzl/oracle-xe

**Comment by filiphr** [comment]
Thanks a lot for doing this @gvenzl. I am glad I could help :)
