### ISSUE TITLE
Support ORACLE_DATABASE

### ISSUE THREAD

**Issue by bahusoid** [gvenzl/oci-oracle-xe#23]
Should work similar to [MYSQL_DATABASE](https://hub.docker.com/_/mysql) 
This variable is optional and allows you to specify the name of a database to be created on image startup. If a user/password was supplied then that user will be granted superuser access (corresponding to GRANT ALL) to this database.

**Comment by gvenzl** [comment]
Hey @bahusoid, thanks for that ER, I like it! Just came across a use case for that as well when trying to get some GitHub Actions to run. Will look into it, should not be too hard.

**Comment by gvenzl** [comment]
Implemented, new pluggable databases can now be created via the `-e ORACLE_DATABASE=<your_DB_name>` option at container startup.
