### ISSUE TITLE
ORA 28040 No matching Authentication Protocol 

### ISSUE THREAD

**Issue by admin-relu** [gvenzl/oci-oracle-xe#230]
`docker run -d -p 1521:1521 -e ORACLE_PASSWORD=123456 -v oracle-volume:/opt/oracle/oradata -v /Users/jpsl/DosPlayas-backup:/opt/backup gvenzl/oracle-xe \n`

Already tried setting env variables to lower version but the error persists:
-e SQLNET.ALLOWED_LOGON_VERSION_CLIENT=8 
-e SQLNET.ALLOWED_LOGON_VERSION_SERVER=8 

how do I fix this?

**Comment by gvenzl** [comment]
Hi @admin-relu,

Thanks for using these images!

Both of these parameters are, as per [Oracle documentation](https://docs.oracle.com/en/database/oracle/oracle-database/19/netrf/parameters-for-the-sqlnet.ora.html#GUID-2041545B-58D4-48DC-986F-DCC9D0DEC642), to be set in the `sqlnet.ora` file, and not as environment variables.

You can find the `sqlnet.ora` file under `<your volume>/dbconfig/XE/sqlnet.ora`
