### ISSUE TITLE
Apple silicon support

### ISSUE THREAD

**Issue by bart-kors** [gvenzl/oci-oracle-xe#244]
Now there is a version of oracle database that runs on Apple silicon:
image: container-registry.oracle.com/database/enterprise:19.19.0.0

would be helpfull to support Apple silicon

**Comment by gvenzl** [comment]
Hi @bart-kors,

Thanks a lot for your interest in these images!

Unfortunately, there is neither an Oracle Database 19c XE, nor any XE version that is available for ARM.

Thanks,

**Comment by Fleury93** [comment]
Ohh sorry, I realized that some time after I asked. So maybe if 23c Free will be released can be included to gvenzl/oracle-free. 

Thanks.

**Comment by gvenzl** [comment]
That's the plan, yes. :)
