### ISSUE TITLE
Running Oracle as sibling / child container in podman - Oracle database startup failing

### ISSUE THREAD

**Issue by gshenoy123** [gvenzl/oci-oracle-xe#246]
In our CI / CD pipeline, and **_the agents are run as Kubernetes pods using rootless podman_**.  In our application / solution we want to execute few test cases and for this we would like to spin up lite weight oracle XE and execute few SQL statements against the database in CI stage.  We tried spinning [21 slim fast container](https://github.com/gvenzl/oci-oracle-xe/blob/main/Dockerfile.faststart), but we are getting startup error, for which logs are attached.  

The error is thrown at [line](https://github.com/gvenzl/oci-oracle-free/blob/eae7d95203cafd152939b4881df14e13bb87f502/container-entrypoint.sh#L327), we can see that services are started but the database is not started. But when we run the podman using root user the database is starting up and test containers are working fine.  Any pointers on this are highly appreciated.

```
CONTAINER: starting up...
CONTAINER: first database startup, initializing...
CONTAINER: uncompressing database data files, please wait... 
CONTAINER: done uncompressing database data files, duration: 9 seconds.
CONTAINER: starting up Oracle Database...
 
LSNRCTL for Linux: Version 21.0.0.0.0 - Production on 14-FEB-2024 15:59:33 
Copyright (c) 1991, 2021, Oracle.  All rights reserved. 
Starting /opt/oracle/product/21c/dbhomeXE/bin/tnslsnr: please wait... 
TNSLSNR for Linux: Version 21.0.0.0.0 - Production
System parameter file is /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/podmanpodnonroot/listener/alert/log.xml

Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521))) 
Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC_FOR_XE)))

STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 21.0.0.0.0 - Production
Start Date                14-FEB-2024 15:59:33
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           XE
Listener Parameter File   /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/podmanpodnonroot/listener/alert/log.xml

Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully

ERROR:

ORA-12547: TNS:lost contact 
SP2-0306: Invalid option.

Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
SP2-0306: Invalid option.

Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
SP2-0157: unable to CONNECT to ORACLE after 3 attempts, exiting SQL*Plus

```

**Comment by gvenzl** [comment]
Hi @gshenoy123,

Thanks a lot for using these images!

This error `ORA-12547: TNS:lost contact` usually indicates a crash of the database due to some other reason. It is common when, for example, trying to run Oracle Database on ARM chips as some x86 instructions don't get translated properly and cause a core dump.

Could you please provide more details about the Kubernetes environment? Is this an x86 cluster or another chip architecture? What's the version of the container runtime?

Ideally, we will also need the database alert log, located under `/opt/oracle/diag/rdbms/xe/XE/trace/alert_XE.log` inside the container.

**Comment by mailtoyasi** [comment]
Hi gvenzl, Thank you for your response. We will provide the details soon.

Meantime, Would like to understand about the permission required for running oracle database server.  
Do we need **_root_** user permission to run this image?

**Comment by gvenzl** [comment]
Hi @mailtoyasi,

No, root user permissions are not required to run these images.
I run them always in rootless podman with my local Unix user
