### ISSUE TITLE
Do you have the image 19c-slim

### ISSUE THREAD

**Issue by armandoruizgonzalez** [gvenzl/oci-oracle-xe#247]
Hi Nicolas,

First of all, thank you very much for the different Oracle images that you publish in git.
I ask you a question: I was recently put to work with Oracle 19-Slim. But I see that in the supported tags section there are all the versions except the **19c-slim** image, is it for some reason?

I am taking information from this site

I would appreciate if you have the image of the 19c-slim

https://github.com/gvenzl/oci-oracle-xe

**Comment by mprins** [comment]
There is no XE edition of version 19c, only the enterprise edition exists which cannot be redistributed due to licensing restrictions

**Comment by armandoruizgonzalez** [comment]
Thank you very much for the reply.

**Comment by mrmanc** [comment]
> There is no XE edition of version 19c, only the enterprise edition exists which cannot be redistributed due to licensing restrictions

Thanks for this comment!

I know this image is deprecated, but it would have saved me a lot of time if the README mentioned that there’s no such thing as XE version 19c in the README 😄
