### ISSUE TITLE
can i change oracle xe 11g NLS_LANG to other

### ISSUE THREAD

**Issue by SingerThailand** [gvenzl/oci-oracle-xe#248]
please help currently image oracle-xe:11g is default NLS_LANG = american_america.al32utf8
but i need to use american_america.th8tisascii how to ?

**Comment by gvenzl** [comment]
Hi @SingerThailand,

Thank you very much for using these images.

NLS_LANG is an environment variable and as such, you can change NLS_LANG by simply providing it via the `-e` / "environment" option:

`podman run -e NLS_LANG=american_america.th8tisascii ...`
