### ISSUE TITLE
Starting docker image with different owner

### ISSUE THREAD

**Issue by kaosanfr** [gvenzl/oci-oracle-xe#252]
Hello,

Please, I would like to know how to launch the docker image, in order to connect to a specific database OWNER.
Thanks in advance

**Comment by gvenzl** [comment]
Hey @kaosanfr,

You can use the `APP_USER` and `APP_USER_PASSWORD` environment variables to create a specific database user, for example: `docker run --name test -p 1521:1521 -e APP_USER=test -e APP_USER_PASSWORD=LetsTest1 gvenzl/oracle-xe:slim`

That will start a container that will have a database user `test` with password `LetsTest1` inside it to which you can connect via the following connect string: `test/LetsTest1@localhost/xepdb1`

Hope this helps!
