### ISSUE TITLE
ERROR ORA-40238: invalid linear algebra shared library /opt/oracle/product/18c/dbhomeXE/lib/libora_netlib.so

### ISSUE THREAD

**Issue by rockgarden** [gvenzl/oci-oracle-xe#31]
When I use gvenzl/oracle-xe:18-full run on macOS Big Sur(11.7), I get the Error.

command  see below:

`% docker run -d -p 1521:1521 -e ORACLE_PASSWORD=oracleAdmin -v oracle-volume:/opt/oracle/oradata gvenzl/oracle-xe:18-full`

**Comment by gvenzl** [comment]
Closing due to lack of response.
