### ISSUE TITLE
jOOQ as user of your images

### ISSUE THREAD

**Issue by lukaseder** [gvenzl/oci-oracle-xe#35]
[jOOQ](https://www.jooq.org) is using your images in integration tests, if you want, you can list it in the "Users of these images" section:
https://hub.docker.com/r/gvenzl/oracle-xe

I don't have a commit to share with you, as the tests are not publicly available

**Comment by gvenzl** [comment]
Got jOOQ on the ReadMe now :)

**Comment by lukaseder** [comment]
Perfect. Thanks again for doing this! Makes my life so much easier! :)
