### ISSUE TITLE
Docker's engine (network) doesn't support Oracle's 19+ Out Of Break bands

### ISSUE THREAD

**Issue by nicolas-tg-ch** [gvenzl/oci-oracle-xe#38]
As pointed out by
https://franckpachot.medium.com/19c-instant-client-and-docker-1566630ab20e
and especially
https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/FAQ.md#ora-12637-packet-receive-failed
there can be an issue with Docker 19+ and Oracle 19+.
I encountered this with Debian 11 as a host, Docker version 20.10.10 and gvenzl/oracle-xe:21-full. Symptoms: connecting to the database **inside** the container via sqlplus works, but from outside (from the host) you only get timeouts and ORA-12637 or similar errors in the server log.

Solution: disable Out Of Bands feature by executing (inside the container)
`echo DISABLE_OOB=ON >> $ORACLE_BASE_HOME/network/admin/sqlnet.ora`
or similar. This can be done on the client side too according to above sources.

**Comment by gvenzl** [comment]
Instead of documenting this, the 21c+ images now have `DISABLE_OOB=ON` set.
