### ISSUE TITLE
Reduce PDB$SEED UNDO and TEMP tablespaces

### ISSUE THREAD

**Issue by loiclefevre** [gvenzl/oci-oracle-xe#39]
The current 21-full image comes with an UNDO tablespace and a TEMP tablespace that are taking space. This slows down the PDB provisioning process. It would be great to have the minimum size being used for each:
- 4 MB for UNDO
- 2 MB for TEMP

**Comment by gvenzl** [comment]
Hi @loiclefevre,

The full images are kept as close as possible to the out-of-the-box installation provided by the Oracle DB installation RPM file to allow for further customization of the default install. The UNDO and TEMP tablespaces are both shrunk for the CDB, PDB$SEED and XEPDB1 for the regular and slim images.
