### ISSUE TITLE
insufficient privileges to execute statement needing SYSDBA privileges

### ISSUE THREAD

**Issue by tomdevroomen** [gvenzl/oci-oracle-xe#41]
Hi,

Now a test user has been introduced, but I'm not able to setup my database correctly now.
Using your container with testcontainers and need to create tablespaces to be able to initiale database.

How would I set this up correctly?

Thank you for your assistance.

**Comment by gvenzl** [comment]
Hi @tomdevroomen,

The user that is created by the `$APP_USER` facility only has schema level rights. These are the rights where the user can create objects in its own schema, specifically:

> CONNECT, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW

The user does not have any administration rights granted to prevent applications from starting to rely on super-user privileges during their tests that they might not have been granted in production.

To create additional tablespaces and perform any other database setup tasks, the [Initializaton scripts](https://github.com/gvenzl/oci-oracle-xe#initialization-scripts) facility should be used instead. These scripts are all executed as a super-user without having to know or specify any username or password. It does require a volume with the scripts being mounted in the container under `/container-entrypoint-initdb.d`.

**Comment by tomdevroomen** [comment]
Hi, let's close this one and continue here: https://github.com/testcontainers/testcontainers-java/issues/4615
