### ISSUE TITLE
Document usage of DISABLE_OOB to work around Docker proxy bug

### ISSUE THREAD

**Issue by gvenzl** [gvenzl/oci-oracle-xe#43]
Report from [vas_stergioulis](https://twitter.com/vas_stergioulis):

When trying with sqlcl, outside of the container, to connect with the host's external ip (internet ip) it connects correctly but when I try instead with 'localhost' or hostname (meaning that it tries with 127.0.0.1), first it asks for the password and after exactly 60 seconds fails with 'IO Error: Got minus one from a read call (CONNECTION_ID=4QZ+EVjLRSeHLmjNPjDj4Q==)'.  The same machine is running in a container a 18c-xe and connecting with localhost works as it should. Listener log.xml in both shows a '* establish * xepdb1 *'   but in failed attempt it writes immediately '* service_update * XE * 0'.

Putting tcp.validnode_checking = no in sqlnet.ora changes the error, immediately shows ORA-12514, TNS:listener does not currently know of service requested in connect descriptor

In general, it is an error that happens with 127.0.0.1 When I use a server name that resolves in external ip6 or ip4 address connects as it should.

**Comment by vassterg** [comment]
Trying with ./sqlcl/bin/sql sys@localhost:1521/xepdb1?oracle.net.disableOob=true as sysdba works as is suggested by you @gvenzl and in [oracle/docker-images/issues/1663](https://github.com/oracle/docker-images/issues/1663#issuecomment-845558513). This workaround is not tested against other scenarios like connections from ords but...

**Comment by gvenzl** [comment]
Great, happy to hear (sort of) that it's the same issue! Will make sure that the `OOB` issue gets documented appropriately!

**Comment by gvenzl** [comment]
This is related to #38.

**Comment by gvenzl** [comment]
@vassterg, this issue gets reported by more and more users taking up 21c, which makes me think that I will probably enable this parameter by default in these images so that users don't have to go through a lot of pain and troubleshooting just to connect to the database.

**Comment by vassterg** [comment]
That would be great!

Στις Παρ, 12 Νοε 2021, 4:42 μ.μ. ο χρήστης Gerald Venzl <
***@***.***> έγραψε:

**Comment by vassterg** [comment]
My main use is with APEX and ORDS. For ORDS config this means that it needs
to use customURL as connect string and this is a change in all
configuration scripts and of course a change in Ansible recipes. So
something reverting the new behavior is welcomed. Thank you.

Στις Παρ, 12 Νοε 2021, 4:45 μ.μ. ο χρήστης Βασίλης Στεργιούλης <
***@***.***> έγραψε:

**Comment by gvenzl** [comment]
According to https://oracle-l.freelists.narkive.com/6bkLfg9i/anyone-have-disable-oob-on-set-in-sqlnet-ora, setting `DISABLE_OOB` can have a negative impact on performance (although it's not discussed/shared how much that impact would be). There is an accompanying parameter `BREAK_POLL_SKIP` that might need to have a higher value set than the default of 4, which is the number of network packets sent before the stack polls for these network break messages.

[Oracle's BI server](https://docs.oracle.com/middleware/12211/biee/BIEMG/GUID-60EF69AB-51D7-47AB-8288-95F8F617FA13.htm#setup_olap_datasrc) documentation refers to setting this to 10k packages:

> Configuring Oracle BI Server When Using a Firewall
The presence of a firewall between the Oracle BI Server and the Oracle Database can result in very long query times.
> 
> For example, if using a simplenqcmd query takes two to three minutes to return results, or if Answers does not respond after executing or validating a SQL statement initiated in Presentation Services.
> 
> To improve query time, go to the sqlnet.ora file in BI_DOMAIN\config\fmwconfig\bienv\core and add the BREAK_POLL_SKIP and DISABLE_OOB parameters as follows:
> 
> BREAK_POLL_SKIP=10000
> DISABLE_OOB=ON 
> This configuration only needs to be performed on the Oracle BI Server. This configuration is not needed on the Oracle Database or on user client desktops.

**Comment by gvenzl** [comment]
Yeah indeed, a lot of people would have to change their configuration to deal with this. Better if the image itself deals with it once, rather than pushing the burden to 1000s of users! :)

**Comment by gvenzl** [comment]
This is fixed now, `DISABLE_OOB` is now turned on in all 21c+ images
