### ISSUE TITLE
How do I connect to a GitHub Action

### ISSUE THREAD

**Issue by theory** [gvenzl/oci-oracle-xe#45]
I appreciate the GitHub Actions example in the README, but I'm struggling to figure out [how to connect](https://github.com/sqitchers/sqitch/runs/4128793641?check_suite_focus=true). Would it be possible to extend the example to show how to connect to the Service Container?

**Comment by theory** [comment]
I worked it out, for 11-slim and 18-slim at least:

*   Set `ORACLE_PASSWORD` when starting the service
*   Use the following parts to connect:
    *   username: `system`
    *   password: As set in `ORACLE_PASSWORD`
    *   host: `127.0.0.1`
    *   port: As mapped or `${{ job.services.oracle.ports[1521] }}`
    *   database/sid: `XE`

Worked out once I found flowable/flowable-engine@18c751f.

**Comment by gvenzl** [comment]
Hi @theory,

Yes, that for sure could be a helpful addition for other users!
Was that information that you posted above enough for you to figure out how to connect or was there anything else missing that you think could help users to ramp up quicker?

**Comment by theory** [comment]
Yes, I think so.

**Comment by theory** [comment]
Although it does not work for me for 21, sadly. The [error is](https://github.com/sqitchers/sqitch/runs/4132636328?check_suite_focus=true):

```
ORA-12637: Packet receive failed (DBD ERROR: OCIServerAttach)
```

I wonder if the health checks aren't keeping it running or something.

**Comment by gvenzl** [comment]
Hey @theory, we just discovered a bad network bug/issue with Docker that prevented users from connecting from the outside world over at #43. Although `ORA-12637: Packet receive failed` didn't show up as a symptom, it would fit the general issue of not being able to connect. I've just uploaded new image versions that work around that issue. Could you perhaps try again and see whether the issue is also fixed for you, more out of curiosity than anything.

**Comment by theory** [comment]
That does seem to have [fixed the issue](https://github.com/sqitchers/sqitch/runs/4203860067?check_suite_focus=true), as I have a new permissions error to work with (presumably the system user does not have permission to write to the gsmuser schema; I'll find one it can write to). Thanks!

**Comment by theory** [comment]
And the (an) [answer is ggsys](https://github.com/sqitchers/sqitch/actions/runs/1459079814)! Thank you!

**Comment by gvenzl** [comment]
Oh that's awesome, congrats and glad to hear!

Hm, [`GGSYS` is an internal user that is used for GoldenGate](https://docs.oracle.com/en/database/oracle/oracle-database/21/ladbi/oracle-database-system-privileges-accounts-and-passwords.html#GUID-7513171C-1055-48BB-8C79-B27EECC9B7E9). It shouldn't be used for anything else.

Your error above showed:

> ORA-01950: no privileges on tablespace 'USERS' (DBD ERROR: error possibly near <*> indicator at char 21 in '
>        INSERT INTO <*>releases (version, installed_at, installer_name, installer_email)
>        VALUES (:p1, current_timestamp, :p2, :p3)

which means that the user didn't have a quota on the tablespace `USERS`.
However, the `SYSTEM` user does have the `UNLIMITED TABLESPACE` privilege, so that should not cause the issue.
If you like, I'm happy to help you investigate this further.

**Comment by theory** [comment]
Yeah, it seems weird that the `system` user can't just create objects and write to them in whatever schema it wants. I've now switched to the `21` image and `ggsys` didn't work anymore, either. So I wrote a little routine that selects all the users and tries to create a table in each user's schema and insert into it. The results for the 21 image, again connected to the XE SID and using there system user:

```
    # SYS: fail
    # AUDSYS: fail
    # SYSTEM: success
    # SYSBACKUP: success
    # SYSDG: fail
    # SYSKM: fail
    # SYSRAC: fail
    # OUTLN: success
    # GSMADMIN_INTERNAL: success
    # GSMUSER: fail
    # GSMROOTUSER: fail
    # DIP: fail
    # XS$NULL: fail
    # REMOTE_SCHEDULER_AGENT: fail
    # DBSFWUSER: success
    # ORACLE_OCM: fail
    # SYS$UMF: fail
    # DGPDB_INT: fail
    # DBSNMP: success
    # APPQOSSYS: success
    # GSMCATUSER: fail
    # GGSYS: success
    # XDB: fail
    # ANONYMOUS: fail
    # CTXSYS: success
    # DVSYS: success
    # MDSYS: success
    # MDDATA: fail
    # LBACSYS: success
    # DVF: fail
    # OPS$ORACLE: fail
```

So I just picked one.

**Comment by gvenzl** [comment]
Hm, interesting, that script shows `SYSTEM` as a success though.

Is there any reason why you could not just use the `$APP_USER` environment variable and connect with that user?
Or is it because you can so far still only connect to the SID (in which the APP_USER is not being created).

**Comment by theory** [comment]
That's what I do for the 11 image, since the user is created in XE. So yes, it's becauseI'm using a sid. I could make it work with `TWO_TASK`, I expect, but what I have works for now.

**Comment by gvenzl** [comment]
Let's continue this conversation over at #46.
Btw, I added the additional details to the [README.md](./README.md) under the GitHub Actions section.
Do these details make sense to you?

**Comment by theory** [comment]
Yeah, that looks great, thank you.

**Comment by gvenzl** [comment]
Awesome, thanks a lot for the confirmation, @theory!
