### ISSUE TITLE
Shell scripts install.*.sh need to have execution rights after git clone

### ISSUE THREAD

**Issue by loiclefevre** [gvenzl/oci-oracle-xe#50]
Cloning the repo, the install.*.sh scripts would need to have execution rights to allow the buildContainerImage.sh to run properly (the docker COPY command would then copy execution rights as well making /install/install.*.sh command run without error).

Without this change, I did get:
STEP 5: RUN /install/install.2130.sh "${BUILD_MODE}"
/bin/sh: /install/install.2130.sh: Permission denied
error building at STEP "RUN /install/install.2130.sh "${BUILD_MODE}"": error while running runtime: exit status 126
ERRO[0013] exit status 126

**Comment by gvenzl** [comment]
Fixed.
