### ISSUE TITLE
Re-running container fails

### ISSUE THREAD

**Issue by astb01** [gvenzl/oci-oracle-xe#55]
Used docker-compose to start container for 18.4.0. On the first start up everything is fine.

When stopping the container and removing it, on subsequent usage I get this in the docker logs:

`ORA-01157: cannot identify/lock data file 19 - see DBWR trace file`

**Comment by astb01** [comment]
Docker-compose used:

`---
version: '3'

services:
    risk-oracle-db:
        container_name: risk-oracle-db
        image: gvenzl/oracle-xe:18.4.0
        ports:
            - 1521:1521
        volumes:
            - oradata:/opt/oracle/oradata
            - ./schema:/container-entrypoint-initdb.d
        environment:
            ORACLE_RANDOM_PASSWORD: 'y'
            APP_USER: test
            APP_USER_PASSWORD: test

volumes:
    oradata:`

local `schema` folder contains an `init.sql` script

**Comment by gvenzl** [comment]
Hi @astb01,

I tried to replicate this issue but was not able to.
Following were my steps, using your `docker-compose.yml` example:

1) `docker-compose up`
  This worked as expected, creating a new volume and starting up the database
1) `docker-compose down`
  This kills the container (prematurely after 10 seconds) and removes it
1) `docker-compose up`
  This restarts the database by creating a new container and attaching the volume to it.

Could you please share your `init.sql` file or tell me whether you are creating any data files in that `init.sql` script? I have a hunch that there is a data file being created outside of `/opt/oracle/oradata/XE/XEPDB1` which then is not persisted inside the volume but inside in the container and consequently dropped with the container. Then on the next startup, the database knows of a data file to be there but can no longer find it.

**Comment by astb01** [comment]
Hi @gvenzl - thanks for your prompt response.

My `init.sql` looks like this:

`ALTER SESSION SET CONTAINER=XEPDB1;

CREATE USER test IDENTIFIED BY test QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO test;

CREATE TABLESPACE myworktbs DATAFILE 'myworktbs.dbf' size 100M autoextend on next 10M maxsize 200M;
CREATE USER myuser IDENTIFIED BY mypass DEFAULT TABLESPACE myworktbs QUOTA 200M ON myworktbs;
GRANT create session TO myuser;
GRANT create table TO myuser;
GRANT create view TO myuser;
GRANT create any trigger TO myuser;
GRANT create any procedure TO myuser;
GRANT create sequence TO myuser;
GRANT create synonym TO myuser;
`

I'm no Oracle expert so I imagine that the init.sql is not compatible for your container? 

@gvenzl - I also found that when trying to re-use the same `oracle_data` volume, I kept getting 'database not open' messages?

My docker-compose.yml is:

`oracle-risk-db:
     container_name: dev-oracle-db
     image: gvenzl/oracle-xe:18.4.0-full
     network_mode: host
     ports:
       - 1521:1521            
     volumes:
       - oracle_data:/opt/oracle/oradata
       - ./database/oracle:/container-entrypoint-startdb.d
     environment:
       ORACLE_RANDOM_PASSWORD: 'yes'
       APP_USER: 'test'
       APP_USER_PASSWORD: 'test'

volumes:
   oracle_data:
`

**Comment by gvenzl** [comment]
Hi @astb01,

I think I see the issue there, could you change the following line:

```sql
CREATE TABLESPACE myworktbs DATAFILE 'myworktbs.dbf' size 100M autoextend on next 10M maxsize 200M;
```
to
```sql
CREATE TABLESPACE myworktbs DATAFILE '/opt/oracle/oradata/XE/XEPDB1/myworktbs.dbf' size 100M autoextend on next 10M maxsize 200M;
```

You will, unfortunately, have to drop the old volume and create a brand new one, otherwise, you will not be able to get the database up and running again.
Do please go ahead and run `docker-compose down` and `docker volume rm oracle_data ` before you try with the changed `init.sql` file. I think this will also solve your 'database not open' issue as well.

Thanks,

**Comment by astb01** [comment]
@gvenzl - Changing the `init.sql` as suggested has done the trick! Many thanks for this .... spent hours trying to figure this out 👍
