### ISSUE TITLE
Image used by Upscheme

### ISSUE THREAD

**Issue by aimeos** [gvenzl/oci-oracle-xe#56]
Proudly using your oracle-xe image in Aimeos Upscheme: https://upscheme.org

https://github.com/aimeos/upscheme/commit/954650afc92273f73bc1276aa0bd2f4253987c4f

**Comment by gvenzl** [comment]
This is great, thanks so much for using these images, @aimeos!

**Comment by gvenzl** [comment]
Added to the ReadMe :)
