### ISSUE TITLE
Support for multiple pdbs in ORACLE_DATABASE

### ISSUE THREAD

**Issue by jmichler** [gvenzl/oci-oracle-xe#58]
As I understand even XE Database allows for up to 3 pdbs. Wouldn't it be convenient to pass up to 3 pdbs names into ORACLE_DATABASE?

**Comment by gvenzl** [comment]
Hi @jmichler, actually, starting with 21c, XE no longer has any restrictions on the number of PDBs.

However, `ORACLE_DATABASE` was not introduced to provide an easy way to provision multiple PDBs at once, or clone from others, etc. It is a variable that allows a user to provide a database name to connect to if for whatever reason `XEPDB1` is not good enough.

It falls in line with other images that provide a similar mechanism, like [MySQL](https://hub.docker.com/_/mysql/):

> MYSQL_DATABASE
This variable is optional and allows you to specify the name of a database to be created on image startup. If a user/password was supplied (see below) then that user will be granted superuser access (corresponding to GRANT ALL) to this database.

Or [Postgres](https://hub.docker.com/_/postgres/):

> POSTGRES_DB
This optional environment variable can be used to define a different name for the default database that is created when the image is first started. If it is not specified, then the value of POSTGRES_USER will be used.

If a user wants to provision multiple PDBs, the [initialization scripts](https://github.com/gvenzl/oci-oracle-xe/blob/main/README.md#initialization-scripts) mechanism should be used instead. This also allows the user to create additional database users, grant privileges on those PDBs to them, and much more.
