### ISSUE TITLE
Add rsim/oracle-enhanced and rsim/ruby-plsql to users of these images

### ISSUE THREAD

**Issue by yahonda** [gvenzl/oci-oracle-xe#66]
Thanks for providing `gvenzl/oracle-xe` Docker image. I'd like these two repositories to be listed to https://github.com/gvenzl/oci-oracle-xe#users-of-these-images .

* rsim/oracle-enhanced via
https://github.com/rsim/oracle-enhanced/commit/afd7a93470d1444e1462d0fb4f3d965ef2698384

* rsim/ruby-plsql via
https://github.com/rsim/ruby-plsql/commit/63baad0b6f8ea0caa4b787f85ffae349dede480a

Thanks.

**Comment by gvenzl** [comment]
Great, thanks for using these images! Will get these repos listed! :)

**Comment by gvenzl** [comment]
Added to ReadMe
