### ISSUE TITLE
Use of container secrets needs amending

### ISSUE THREAD

**Issue by martincarstenbach** [gvenzl/oci-oracle-xe#69]
# Problem Statement 

The section about container secrets in `readme.md` might need updating. The way Docker Engine (tested with 20.10.12 on Ubuntu 20.04 LTS) handles secrets is different from `podman` (tested with podman 3.3.1 on Oracle Linux 8.5).

# Docker Engine

For secrets to be available you need to initialise a (single node) Docker Swarm. Otherwise it's not possible to create the secret:
```
$ sudo docker secret create oracle-passwd ~/.pwd
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```
Once the swarm is initialised it is possible to add the secret:

```
$ sudo docker swarm init
Swarm initialized: current node (1rzudangjm68u30vx51227zf6) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-5ezmfxh6tzi7v4789vi0l8gjq2m1n1zzyiuluets9cawph849w-0soqtexxpbd3blrsygp7qchpi 10.0.2.15:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
```
Now it's possible to create a secret:
```
$ sudo docker secret create oracle-passwd ~/.pwd
dkh6i7frg9cstd8zn7izflbjm
$ sudo docker secret ls
ID                          NAME            DRIVER    CREATED          UPDATED
dkh6i7frg9cstd8zn7izflbjm   oracle-passwd             11 seconds ago   11 seconds ago
```
Without passing the secret on the command line /run/secrets/* does not contain any data and the container fails to start:

```
$ sudo docker run --name some-oracle -e ORACLE_PASSWORD_FILE=/run/secrets/oracle-passwd --rm -it gvenzl/oracle-xe:21-slim
CONTAINER: starting up...
/opt/oracle/container-entrypoint.sh: line 70: /run/secrets/oracle-passwd: No such file or directory
```
The error message in container-entrypoint.sh refers to a missing `/run/secrets/oracle-passwd` file

Unfortunately it seems impossible to pass the secret to `docker run`:

```
$ sudo docker run --name some-oracle -e ORACLE_PASSWORD_FILE=/run/secrets/oracle-passwd --rm -it --secret oracle-passwd gvenzl/oracle-xe:21-slim
unknown flag: --secret
See 'docker run --help'.
```
Passing secrets requires a service to be started:

```
$ sudo docker service create --name some-oracle -e ORACLE_PASSWORD_FILE=/run/secrets/oracle-passwd --secret oracle-passwd gvenzl/oracle-xe:21-slim
6qkawq9wg3r25uv6ashoajzs1
overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Service converged 
$ sudo docker service ls
ID             NAME          MODE         REPLICAS   IMAGE                      PORTS
6qkawq9wg3r2   some-oracle   replicated   1/1        gvenzl/oracle-xe:21-slim   

$ sudo docker container exec $(sudo docker ps --filter name=some-oracle -q) ls -l /run/secrets
total 4
-r--r--r-- 1 root root 7 Dec 14 15:09 oracle-passwd
```
# Podman

The use of `podman` greatly simplifies matters. It is possible to create a secret without the need of any auxiliary construct. A simple `podman secret create some-secret ~/.pwd` will do. The secret can be passed as an argument to `podman run` as in

```shell
$ podman run --name some-oracle \
  --secret oracle-password \
  -e ORACLE_PASSWORD_FILE=/run/secrets/oracle-password \
  -d docker.io/gvenzl/oracle-xe:21-slim
```

Unless the secret is passed to either Docker service or podman it won't be accessible in `/run/secrets/*`

**Comment by gvenzl** [comment]
Hi @martincarstenbach,

Thanks a lot for this great write-up on how to use secrets with Docker. After some research, I found that the different containerization technologies use rather different approaches for handling secrets (Docker, Podman, Kubernetes).

I feel that the ReadMe for these images on how to use them is not the right place to educate people on how the secrets mechanism in all the different containerization technologies works. Also because Docker Hub has a 20k character limit for the ReadMe as I found out some months ago. I have therefore opted for linking to the official documentation of said three containerization technologies above, rather than documenting the details on how to create and use secrets for all three technologies.

Thx,
