### ISSUE TITLE
Do we need to create manually /docker-entrypoint-startdb.d using gvenzl/oracle-xe:21-full?

### ISSUE THREAD

**Issue by jesusmorenodiaz** [gvenzl/oci-oracle-xe#74]
we use this run command to start a new 21c XE...

docker run -d --name your_name -p $PORT1:1521 -p $PORT2:5500 -p $PORT3:8080 -p $PORT4:8181 \
-v your_container_home/scripts/startup:/opt/oracle/scripts/startup \
-v your_container_home/scripts/setup:/opt/oracle/scripts/setup \
-v your_container_home:/opt/oracle/oradata \
-e ORACLE_PASSWORD=your_password \
gvenzl/oracle-xe:21-full

here is connected local path 'your_container_home/scripts/startup' to container directory /opt/oracle/scripts/startup

we created a symlink in root directory in container, /docker-entrypoint-startdb.d to /opt/oracle/scripts/startup in order to exec scripts inside

if you do not create this link, scripts are not executed.

if you put an "echo command" inside /opt/oracle/container-entrypoint.sh, prior to line #237, that is...
    echo "";
    echo "CONTAINER: Executing user defined scripts in ${SCRIPTS_ROOT}..."

you receive echoed "/docker-entrypoint-startdb.d" as SCRIPTS_ROOT

So the question is: do we need to create a symlink /docker-entrypoint-startdb.d to /opt/oracle/scripts/startup?

**Comment by gvenzl** [comment]
Hi @jesusmorenodiaz,

Container initialization scripts have to be mounted under `/container-entrypoint-initdb.d` (see [Initialization Scripts](https://github.com/gvenzl/oci-oracle-xe#initialization-scripts) in the ReadMe).
Likewise, container startup scripts have to be mounted under `/container-entrypoint-startdb.d` (see [Startup Scripts](https://github.com/gvenzl/oci-oracle-xe#startup-scripts) in the ReadMe).

So the run command should look as follows:

```bash
docker run -d --name your_name -p $PORT1:1521 -p $PORT2:5500 -p $PORT3:8080 -p $PORT4:8181
-v your_container_home/scripts/startup:/container-entrypoint-startdb.d
-v your_container_home/scripts/setup:/container-entrypoint-initdb.d
-v your_container_home:/opt/oracle/oradata
-e ORACLE_PASSWORD=your_password
gvenzl/oracle-xe:21-full
```

Hope this helps!
