### ISSUE TITLE
update utplsql reference 

### ISSUE THREAD

**Issue by jgebal** [gvenzl/oci-oracle-xe#77]
As we are moving to Github Actions and now leveraging full potential of your images, you might want to update your references for utPLSQL usage:
- utPLSQL https://github.com/utPLSQL/utPLSQL/pull/1175/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721
- utPLSQL-maven-plugin - https://github.com/utPLSQL/utPLSQL-maven-plugin/commit/4d8deeb7f107a52913d6320080b972318e753b0e
- utPLSQL-java-api - https://github.com/utPLSQL/utPLSQL-java-api/pull/102/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721
- utPLSQL-demo-project - https://github.com/utPLSQL/utPLSQL-demo-project/commit/99463f0035c4517a0b42a6ea6a55840c82828e86

**Comment by gvenzl** [comment]
Updated! :)
