### ISSUE TITLE
How can I connect as root?

### ISSUE THREAD

**Issue by evertonfoz** [gvenzl/oci-oracle-xe#79]
Hello, I am using your great Image, but I need install some packages. Can you help me please?

```
bash-4.4$ wget http://www.vpn.net/installers/logmein-hamachi-2.1.0.165-1.x86_4.rpm
bash: wget: command not found
```

**Comment by gvenzl** [comment]
Hi @evertonfoz,

The right containerized approach would be to build a new image of this base image by creating a new Dockerfile looking something like this:

```
FROM gvenzl/oracle-xe:21-full

RUN microdnf install wget
RUN wget http://www.vpn.net/installers/logmein-hamachi-2.1.0.165-1.x86_4.rpm

ENTRYPOINT ["container-entrypoint.sh"]
```

However, there is also always the cheap way of `docker exec -ti -u=0 <container name> bash` which will connect you into the container as user 0, i.e. `root`.

Hope this helps!

**Comment by evertonfoz** [comment]
Hi @gvenzl 

First of all, thank you very much for your feedback. Your repository has been of great help.

I'm new to Docker. I managed to solve this situation, but if you don't mind, is there any way I can run a script, in Docker-compose after your image is fully started? I saw that if I use Entrypoint, it overwrites yours

**Comment by gvenzl** [comment]
Hi @evertonfoz,

Thanks a lot, I'm happy to hear that!

Yeah, the images have an [initialization scripts facility built-in](https://github.com/gvenzl/oci-oracle-xe/blob/main/README.md#initialization-scripts).
If you mount a volume with your scripts under `/container-entrypoint-initdb.d`, these will be executed after the database is setup.

Likewise, if you wish to run some scripts every time the database has started up, you can do the same with the [startup scripts facility](https://github.com/gvenzl/oci-oracle-xe/blob/main/README.md#startup-scripts) mounting scripts under `/container-entrypoint-startdb.d`.

However, neither of these will run as the `root` user but the same user the database runs under.

**Comment by evertonfoz** [comment]
Hi @gvenzl 

Very cool. It worked perfectly here. I apologize for not having read your full documentation carefully. Everything is new, but I'm learning and I'm very grateful for your attention and availability of this container.

**Comment by gvenzl** [comment]
Hey @evertonfoz,

No worries, that's why we have GitHub issues to ask questions :)

Great, glad to hear!
Thank YOU for using these images!
