### ISSUE TITLE
Runnign sonarcloud analysis on docker xe image fails

### ISSUE THREAD

**Issue by jgebal** [gvenzl/oci-oracle-xe#80]
Hi @gvenzl 
I'm trying to implement sonar DB-level analysis as per documentation [here](https://docs.sonarcloud.io/advanced-setup/languages/pl-sql)
I'm facing a [connection issue](https://github.com/utPLSQL/utPLSQL/runs/5074081747?check_suite_focus=true#step:20:137) however:
```
java.io.IOException: Connection refused, socket connect lapse 12 ms. 127.0.0.1 1521  0 (1/1) true
...
java.net.ConnectException: Connection refused
```
You can see this on all 3 versions of DBs.
I use the small images for 11, 18 and 21.

Do you have any clue what could be causing this issue?

**Comment by gvenzl** [comment]
Hm, this is a strange one.
There is certainly an [error that the client cannot establish a connection to the database](https://github.com/utPLSQL/utPLSQL/runs/5074081747?check_suite_focus=true#step:20:171):

> Caused by: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection (CONNECTION_ID=vIHA+MYTSAqYVy2TOy3OOQ==)
	at oracle.jdbc.driver.T4CConnection.handleLogonNetException(T4CConnection.java:872)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:677)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1039)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:90)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:728)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:649)

But the [connect string](https://github.com/utPLSQL/utPLSQL/runs/5074081747?check_suite_focus=true#step:20:129) appears to be fine:

> INFO: Loading Data Dictionary from jdbc:oracle:thin:@127.0.0.1:1521/XE

As this is [the same that utPLSQL](https://github.com/utPLSQL/utPLSQL/runs/5074081747?check_suite_focus=true#step:18:91) is using previously as well:

> Use connection string jdbc:oracle:thin:\*\*\*\*/\*\*\*\*@127.0.0.1:1521/XE

However, there is a difference between the utPLSQL container and the Sonarcloud one.

The [utPLSQL containers](https://github.com/utPLSQL/utPLSQL/runs/5074081747?check_suite_focus=true#step:17:2) are all using `--network host`:

> docker run --rm -v $(pwd):/utPLSQL -w /utPLSQL --network host --entrypoint bash ${DOCKER_ENV} ${ORACLE_VERSION} test/install_tests.sh

While the [Sonarcloud one](https://github.com/utPLSQL/utPLSQL/runs/5074081747?check_suite_focus=true#step:20:67) do not, but instead use the [provided network](https://github.com/utPLSQL/utPLSQL/runs/5074081747?check_suite_focus=true#step:4:12) created by the GHA Container Service:

> /usr/bin/docker network create --label 7db2d7 github_network_9a204ab74b03414f8b301b17ba8a6d39

> /usr/bin/docker create --name 3ca00849d2554f9b8b42f1de627f6094_gvenzloraclexe11full_33b3e4 --label 7db2d7 --network github_network_9a204ab74b03414f8b301b17ba8a6d39 --network-alias oracle -p 1521:1521 --health-cmd healthcheck.sh --health-interval 10s --health-timeout 5s --health-retries 10 -e "ORACLE_PASSWORD=oracle" -e "MATRIX_JOB_ID=1" -e GITHUB_ACTIONS=true -e CI=true gvenzl/oracle-xe:11-full

> /usr/bin/docker run --name db2d7de95d3bdbc6248a3b83d2b5e956087b1_fd06ef --label 7db2d7 --workdir /github/workspace --rm -e ORACLE_VERSION -e CONNECTION_STR -e ORACLE_PASSWORD -e DOCKER_VOLUME -e UT3_DEVELOP_SCHEMA -e UT3_DEVELOP_SCHEMA_PASSWORD -e UT3_RELEASE_VERSION_SCHEMA -e UT3_RELEASE_VERSION_SCHEMA_PASSWORD -e UT3_USER -e UT3_USER_PASSWORD -e UT3_TESTER -e UT3_TESTER_PASSWORD -e UT3_TESTER_HELPER -e UT3_TESTER_HELPER_PASSWORD -e UT3_TABLESPACE -e SQLCLI -e OJDBC_HOME -e OJDBC_URL -e ORACLE_PWD -e TZ -e UTPLSQL_CLI_VERSION -e UTPLSQL_DIR -e UTPLSQL_BUILD_NO_OFFSET -e GIT_AUTHOR_NAME -e GIT_AUTHOR_EMAIL -e GIT_COMMITTER_NAME -e GIT_COMMITTER_EMAIL -e DOCKER_ENV -e CI_REPOSITORY_SLUG -e CI_REPOSITORY_OWNER -e CI_REPOSITORY_OWNER_SLUG -e CI_REPOSITORY_NAME -e CI_REPOSITORY_NAME_SLUG -e CI_REPOSITORY -e CI_REF_SLUG -e CI_REF_NAME -e CI_REF_NAME_SLUG -e CI_REF -e CI_ACTION_REF_NAME -e CI_ACTION_REF_NAME_SLUG -e CI_HEAD_REF_SLUG -e CI_HEAD_REF -e CI_BASE_REF_SLUG -e CI_BASE_REF -e CI_SHA_SHORT -e CI_SHA -e CI_PR_TITLE -e CI_PR_DESCRIPTION -e CI_ACTOR -e CI_EVENT_NAME -e CI_RUN_ID -e CI_RUN_NUMBER -e CI_WORKFLOW -e CI_ACTION -e UTPLSQL_BUILD_NO -e UTPLSQL_VERSION -e UTPLSQL_BUILD_VERSION -e CURRENT_BRANCH -e GITHUB_TOKEN -e SONAR_TOKEN -e INPUT_ARGS -e INPUT_PROJECTBASEDIR -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --network github_network_9a204ab74b03414f8b301b17ba8a6d39 -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/utPLSQL/utPLSQL":"/github/workspace" 7db2d7:de95d3bdbc6248a3b83d2b5e956087b1 -Dsonar.buildString=v3.1.12.3783-develop.1 -Dsonar.plsql.jdbc.url=jdbc:oracle:thin:@127.0.0.1:1521/XE -Dsonar.plsql.jdbc.driver.path=ojdbc/ojdbc8.jar

My hunch is that `127.0.0.1` does not cut it because the container is not using `--network host` but the actual network for in-between container communication.

**Comment by gvenzl** [comment]
I could be wrong, but looking at this example here, I think you have to use the container label `oracle` instead of `127.0.0.1`: https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers

**Comment by jgebal** [comment]
Let me try this and see if it helps.

**Comment by jgebal** [comment]
Github Actions seems to confirm what you're saying.
https://docs.github.com/en/actions/using-containerized-services/about-service-containers#running-jobs-in-a-container

Maybe it's worth referencing/mentioning in your readme?

**Comment by jgebal** [comment]
Solved!
Thank you @gvenzl 
the data-dictionary is [now loading](https://github.com/utPLSQL/utPLSQL/runs/5080464185?check_suite_focus=true#step:21:122) and getting full analysis!

**Comment by gvenzl** [comment]
Awesome, glad to hear!

What do you think could be better in the ReadMe to make this easy to understand for other users?

**Comment by jgebal** [comment]
in readme you mention:

After your service is created, you can connect to it via the following properties:
>...
Host: localhost or 127.0.0.1
Port: 1521
Service name: XEPDB1
Database App User: my_user
Database App Password: my_password_which_I_really_should_change
If you amend the variables above, here is some more useful info:
...

Maybe you could add that this is only valid **within** container
When connecting from **host** you need to use the label of container service (**oracle**).

**Comment by gvenzl** [comment]
But that's not true. When you connect from host (or a container using `--network host` you need these (localhost or 127.0.0.1), as utPLSQL uses them. Only when you connect from another container and you do not use `--network host`, you need the label.

Anyway, will think of something.

Thanks!
