### ISSUE TITLE
How can I change the default charset?

### ISSUE THREAD

**Issue by serathiuk** [gvenzl/oci-oracle-xe#83]
Hello,

There is a way to change the default charset of the Oracle on container? In the docker images in the Oracle repository (https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance), there is the ORACLE_CHARACTERSET parameter. I haven't found something like this in gvenzl/oracle-xe image. I've looked at the project source code and I haven't found an easy solution to change the default charset without build a new docker image. There is a way to change the default charset without build a new image?

**Comment by gvenzl** [comment]
Hi @serathiuk,

No, there is no way to change the default character set in these images.
The character set of an Oracle instance is set during the instance creation.
These images, however, already include a pre-created Oracle instance in the AL32UTF8 character set.

The only way to change that is to create a new image/database.

**Comment by R0Wi** [comment]
In case anyone is interested how to build such a custom image, i created a little [**gist**](https://gist.github.com/R0Wi/be669529a4119dcf80be54cee142e575). Basically (like @gvenzl mentioned) you'll have to run the init process for an empty database with the correct character set settings once and then apply that database root folder to the image here.

**Comment by gvenzl** [comment]
Just be aware that this approach can lead to data corruption if there is data present in the database that cannot be represented by the character set. Won't be the case for an empty database as all data in the data dictionary is essentially ASCII7 but if you have already loaded data into the DB, all bets are off.

**Comment by serathiuk** [comment]
> Just be aware that this approach can lead to data corruption if there is data present in the database that cannot be represented by the character set. Won't be the case for an empty database as all data in the data dictionary is essentially ASCII7 but if you have already loaded data into the DB, all bets are off.

We're running this script on container startup and haven't had any problems (yet?) with it. For development purposes, it's working for us. Thanks for alerting us. :)
