### ISSUE TITLE
Does the last docker image version resolve the log4j venerability? 

### ISSUE THREAD

**Issue by YoussefArfaoui** [gvenzl/oci-oracle-xe#85]
Dear,

Please, does the last docker image version resolve the log4j venerability? 

Kr,
Youssef

**Comment by gvenzl** [comment]
Hi @YoussefArfaoui,

log4j is neither used by Oracle DB XE, nor part of these (21c) images.

**Comment by YoussefArfaoui** [comment]
Hello Gerald,

Clear, many thanks for you reply.

I'm got an error when I tried to pull all your images from docker hub . The error was : **missing signature key**

my docker version 
Client:
Version: 1.13.1
API version: 1.26
Package version: docker-1.13.1-91.git07f3374.el7.x86_64
Go version: go1.10.3
Git commit: 07f3374/1.13.1
Built: Fri Feb 8 20:24:43 2019
OS/Arch: linux/amd64

Server:
Version: 1.13.1
API version: 1.26 (minimum version 1.12)
Package version: docker-1.13.1-91.git07f3374.el7.x86_64
Go version: go1.10.3
Git commit: 07f3374/1.13.1
Built: Fri Feb 8 20:24:43 2019
OS/Arch: linux/amd64
Experimental: true

I don't know if it's only from my side or not. I have googled the error, one possible cause is if one or more properties of the manifest.json file are missing or incorrect.

Please, any idea?

Kr,
Youssef

**Comment by gvenzl** [comment]
Hi @YoussefArfaoui,

The version that you are using is very, very, very old.
Docker's [current version is 20.10 (2021-12-13)](https://docs.docker.com/engine/release-notes/) while [1.13.1 dates back to 2017](https://docs.docker.com/engine/release-notes/prior-releases/).
Could you please update your Docker installation to the latest and try again?

Thanks,

**Comment by YoussefArfaoui** [comment]
Hello Gerald,

Many thanks for you reply.

In fact I have constraint, many machines still using the old docker version. I need to make sure that they can build and pull the  image without any issue 


As workaround, from a more recent machine where podman was installed.


#Pull the image
$ podman pull externalrepository/gvenzl/oracle-xe:21.3.0-slim
#tag the image in the 
$ podman tag externalrepository/gvenzl/oracle-xe:21.3.0-slim internalrepository/v2/gvenzl/oracle-xe:21.3.0-slim
#push the tagged image to the internalrepository with -f v2s2. -f v2s2 is important to make sure that we don't push it back  the dokcer with the same manifest type as the source (oci)
$ podman image push internalrepository/v2/gvenzl/oracle-xe:21.3.0-slim -f v2s2

Then I was able to pull the internalrepository/v2/gvenzl/oracle-xe:21.3.0-slim from all machines and build without any issue.


Thanks

**Comment by gvenzl** [comment]
Hi @YoussefArfaoui, glad to hear that you could work around the old Docker version!

Can we close this question then?

Thanks,

**Comment by YoussefArfaoui** [comment]
Hello @gvenzl ,

Yes please. Many thanks for your support.

Kr,
Youssef
