### ISSUE TITLE
 Import and export of dump files.

### ISSUE THREAD

**Issue by edualdan982** [gvenzl/oci-oracle-xe#86]
I tried to do an imp export with a dump file, but it ends unsuccessfully.
Now try to create tables with a user where I create a tablespace and assign the tablespace to the pluggable XEPD1 with exp but it does not leave, is it some restriction of the 21xe database version?

```
bash-4.4$ imp USER/password1234@localhost:1521/xepdb1 file=archivo.dmp full=y

Import: Release 21.0.0.0.0 - Production on Fri Feb 18 13:33:02 2022
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle and/or its affiliates.  All rights reserved.

Connected to: Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0

Export file created by EXPORT:V19.00.00 via conventional path

Warning: the objects were exported by ADMACUARIO, not by you

import done in [datos.md](https://github.com/gvenzl/oci-oracle-xe/files/8097601/datos.md) character set and AL16UTF16 NCHAR character set
export client uses US7ASCII character set (possible charset conversion)
IMP-00030: failed to create file import_sys for write
IMP-00000: Import terminated unsuccessfully
```

**Comment by gvenzl** [comment]
Hi @edualdan982,

I believe the reason why your import does not work is with this error:
```
> IMP-00030: failed to create file import_sys for write
```

It appears that some write permissions aren't provided but needed.

As to why you cannot create tables with a new user in a new tablespace, it is hard to comment on that without knowing the actual error.

What I can say is that there are no restrictions in 21c XE that would explain any of these.
Certainly creating new tables, users and tablespaces works without any issues.

Thanks,

**Comment by edualdan982** [comment]
It was not a permissions problem, obviously it was a character set problem, change the character set and you can import the dump file but use a different image to raise the base since as I read in the git hub forum of the image you uploaded, where I suggest customizing the image.


I appreciate the time in advance, greetings.
