### ISSUE TITLE
Question: What would it take to build a docker image that has ords and apex on it

### ISSUE THREAD

**Issue by dhaanpaa-lab0** [gvenzl/oci-oracle-xe#88]
Is there a ORDS docker image already? Or can you point me in the direction of what I would need to script and setup an image that would have ords as well as install apex into your XE Database?

**Comment by gvenzl** [comment]
Hi @dhaanpaa-lab0,

Depends on what you are looking for.
I have not built an ORDS image and am not planning on doing so.
However, there is an official ORDS image available at `container-registry.oracle.com/database/ords:latest`.\

Also, my dear friend @fuzziebrain has built an APEX Oracle DB stack on Docker quite a while back, perhaps that one is worth a look: https://github.com/fuzziebrain/docker-apex-stack
