### ISSUE TITLE
utPLSQL builds sometimes fail with ORA-00600 on all of XE containers

### ISSUE THREAD

**Issue by jgebal** [gvenzl/oci-oracle-xe#89]
While building utPLSQL project, I sometimes see that the build is failing with infamous ORA-00600 error.
This happens irregularly and I've seen it happen on all 3 versions (11/18/21XE).
The trouble is, it's not easy to reproduce as it only happens sometimes on some builds with GitHub Actions.
It seems unrelated to the codebase as it happened across time on several occassions.

As discussed on Slack with @gvenzl, I've provided a way to capture the `diag` folder data when the build fails on tests for utPLSQL.
The one thing that seems common is the test that is causing the error to show up.
It always seem to fail, when testing with DBMS_JOB and DDL TRIGGER enabled.

You can see the failures in those builds:
- 11g - [here](https://github.com/utPLSQL/utPLSQL/runs/4709191216?check_suite_focus=true#step:20:1164) fails but the test-run continues despite the failure with ORA-00600 
- 21XE - [here](https://github.com/utPLSQL/utPLSQL/runs/5181779089?check_suite_focus=true) and [here](https://github.com/utPLSQL/utPLSQL/runs/4709261637?check_suite_focus=true#step:20:362) - test run stops
- 18XE - [here](https://github.com/utPLSQL/utPLSQL/runs/5117446995?check_suite_focus=true) - test run stops

You can obtain the `diag` directory content from [here](https://github.com/utPLSQL/utPLSQL/actions/runs/1815145208) - they will disappear automatically after 90 days I think.

**Comment by jgebal** [comment]
[my-artifact$-18XE.zip](https://github.com/gvenzl/oci-oracle-xe/files/8128497/my-artifact.-18XE.zip)
Attaching the mentioned artefact - hope this helps.

**Comment by jgebal** [comment]
@gvenzl 
Is there any chance for investigation of that issue?
I'm monitoring our builds and may provide more updates if the problem goes away after changes done do the unit tests&code as we develop new features.

I am however a bit uneasy to see random, non-deterministic ORA-00600 errors in our test-runs.

**Comment by gvenzl** [comment]
Hi @jgebal,

Apologies, the last couple of weeks have been a bit more busy than usual.

Looking at the trace files, thanks a lot for providing these btw, the error appears at line 124 in `UT3_TESTER_HELPER.ANNOTATION_CACHE_HELPER.CREATE_RUN_FUNCTION_FOR_USER` during something that looks like a recursive call:

```
----- PL/SQL Stack -----
----- PL/SQL Call Stack -----
  object      line  object
  handle    number  name
0x66abddc8       124  package body UT3_TESTER_HELPER.ANNOTATION_CACHE_HELPER.CREATE_RUN_FUNCTION_FOR_USER
0x66abddc8       149  package body UT3_TESTER_HELPER.ANNOTATION_CACHE_HELPER.CREATE_RUN_FUNCTION_FOR_USERS
0x68a91618         6  anonymous block
0x681dc990      1721  package body SYS.DBMS_SQL.EXECUTE
0x83d37808       142  type body UT3.UT_EXECUTABLE.DO_EXECUTE
0x68191a50        57  type body UT3.UT_SUITE.DO_EXECUTE
0x6cca3c98        49  type body UT3.UT_SUITE_ITEM.DO_EXECUTE
0x63823768        51  type body UT3.UT_LOGICAL_SUITE.DO_EXECUTE
0x6cca3c98        49  type body UT3.UT_SUITE_ITEM.DO_EXECUTE
0x68191a50        66  type body UT3.UT_SUITE.DO_EXECUTE
0x6cca3c98        49  type body UT3.UT_SUITE_ITEM.DO_EXECUTE
0x63823768        51  type body UT3.UT_LOGICAL_SUITE.DO_EXECUTE
0x6cca3c98        49  type body UT3.UT_SUITE_ITEM.DO_EXECUTE
0x68191a50        66  type body UT3.UT_SUITE.DO_EXECUTE
0x63a30a28        59  type body UT
```

The ORA-00600 does not provide any arguments, which is very strange, however, the next error message may be the clue to the issue:

```
ORA-00600: internal error code, arguments: [], [], [], [], [], [], [], [], [], [], [], []
ORA-30036: unable to extend segment by  in undo tablespace ''
ORA-06550: line , column :
ORA-06550: line , column :
ORA-06550: line , column :
ORA-06550: line , column :
ORA-06550: line , column :
ORA-06550: line , column :
ORA-06550: line 1, column 1:
PLS-00103: Encountered the symbol "CREATE" when expecting one of the following:

   ( begin case declare exit for function goto if loop mod null
   package pragma procedure raise return select type update
   while with <an identifier>
   <a double-quoted delimited-identifier> <a bind variable> <<
   table continue call close current define delete fetch lock
   insert open rollback savepoint set sql execute commit forall
   merge library assembly operator pipe purge compound
   json_exists json_value json_q
```

Could it be that the container simply runs out of space and cannot extend the `UNDO` tablespace when creating a new object?

**Comment by jgebal** [comment]
Thanks @gvenzl 
I didn't see that error showing up recently and I do find it hard to reproduce.
Closing for now,
I'll re-open if it becomes a permanent issue or will start to show up frequently-enough to be a real pain.
