### ISSUE TITLE
How can i change the charset in a new image

### ISSUE THREAD

**Issue by Pedro-Guilherme** [gvenzl/oci-oracle-xe#92]
Hi,

I tried to create a new image with oracle 11g (file Dockerfile.11202) adding the variable "NLS_LANG = PORTUGUESE_BRAZIL.WE8MSWIN1252" and the database continues to be installed with the default charset...

Does anyone have a hint where I'm going wrong?

**Comment by gvenzl** [comment]
Hi @Pedro-Guilherme,

11g XE is only available in UTF-8, so you can't change the character set. See [here](https://docs.oracle.com/cd/E17781_01/install.112/e18802/toc.htm#BABJACJJ) in the old documentation.

**Comment by R0Wi** [comment]
Hey @gvenzl and thanks for these nice images! 
Just for completeness: can the `NLS_LANG` be set in newer versions of Oracle? I'm currently trying out your `gvenzl/oracle-xe:21.3.0-slim` but i wasn't able to change the default character set by setting the `NLS_LANG` environment variable. I also didn't find anything in the startup- or init-code so i was wondering if this is possible somehow?

**Comment by R0Wi** [comment]
Found a solution, see https://github.com/gvenzl/oci-oracle-xe/issues/83#issuecomment-1128730830
