### ISSUE TITLE
File Permissions and Copying files

### ISSUE THREAD

**Issue by aminadatia** [gvenzl/oci-oracle-xe#96]
Hi

How do I change files permission and Owner for files copied into the 21cFull container. I am trying to install Oracle Kafka from SQLDeveloper. There are files orakafka.properties for example, which when I copy from Ubuntu to 21cFull:<filename>, the owner:group become 1000:1000. I can then not change the ownership or the permission.

**Comment by gvenzl** [comment]
Hi @aminadatia,

Could you please elaborate on how you copy these files into the container?

**Comment by aminadatia** [comment]
Hi

I downloaded SQL Developer and installed on my Windows for Linux. Extracted the Kafka zip file. Installed to XE database. Realized it had to be run from within the Docker Container 21cFull.
I then did cp file-from-wsl to file to 21cFull container location. The file copies but owner is 1000:1000 . I tried to do chown to oracle:oinstall but I get permission denied.
I can go to /opt/oracle and all the directories and files are owned by oracle.

Regards

Regards
Amin Adatia
________________________________

**Comment by aminadatia** [comment]
Hi

I think I have the command as docker cp blah

Regards
Amin Adatia
________________________________

**Comment by gvenzl** [comment]
Hi @aminadatia,

You can `chown` them via the `root` user: `docker exec -u 0 <container> chown ...`

**Comment by aminadatia** [comment]
Hi
Thanks. I will try this

Regards
Amin Adatia
________________________________

**Comment by aminadatia** [comment]
Hi

Excellent! Thank you!
________________________________

**Comment by aminadatia** [comment]
Hi

Do you know how I can install a File Manager and an Editor in the Container 21cFull?

Regards,
Amin
________________________________

**Comment by gvenzl** [comment]
Hi @aminadatia,

Sorry, I do not.
Perhaps https://forums.docker.com/ is a good place to ask that question.

**Comment by aminadatia** [comment]
Hi

Sorry to bother you again.

I am trying to install ORA_KAFKA in the Oracle XE-21c database. I need to have Java 11 in the container. Below is my Dockerfile. None of the RUN options work though.

I have downloaded the openjdk using
docker pull openjdk
but I am now lost as to what to do.

# Start with the Oracle image
FROM gvenzl/oracle-xe:21-full

# we need to be root to do the this
USER root

# Download and install JDK 11
# None of these work
#RUN dnf install java-11-openjdk.x86_64 -y
#RUN apt-get update && apt-get install -y default-jdk
#RUN install openjdk-11-jre openjdk-11-jdk
#

# back to default user
USER 1000

RUN java --version



Regards

________________________________
