### ISSUE TITLE
Oracle 19c and 12c images

### ISSUE THREAD

**Issue by sualeh** [gvenzl/oci-oracle-xe#98]
@gvenzl - Gerald, thank you very much for providing these Docker images! They make development and testing with Oracle so much easier.

Do you have Docker images for Oracle 19c LTE and 12c? If not, any thoughts on adding these?

**Comment by gvenzl** [comment]
Hi @sualeh,

Neither a Oracle Database 12c XE nor Oracle Database 19c XE do exist.

**Comment by sualeh** [comment]
Thanks. Do you have any plans to add them? I was thinking that since Oracle Database 19c XE, would you consider adding that in favor of Oracle Database 18c XE?

**Comment by gvenzl** [comment]
Hi @sualeh,

There was no Oracle Database 19c XE released by Oracle.
Only 18c XE and 21c XE.
So I can't add what doesn't exist, sorry.

**Comment by sualeh** [comment]
@gvenzl - thanks. I did not realize that.

**Comment by gvenzl** [comment]
Sure thing, no worries!
